### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Matikoo0** [AlexProgrammerDE/balena-minecraft-server#1]
when I  log in to the serwer I get a user verification error despite the option turned off online mode in server.proporties.

**Comment by AlexProgrammerDE** [comment]
@Matikoo0 very mysterious. At default the online-mode is in the server.properties file set to true. Do you have any additional info/screenshots? Can you also please check via scp that the option is set to true on your device? Here is a link to the scp guide: https://github.com/AlexProgrammerDE/balena-minecraft-server#connect-to-the-file-directory-satellite

**Comment by AlexProgrammerDE** [comment]
@Matikoo0 are you investigating?

**Comment by Matikoo0** [comment]
Yes

**Comment by Matikoo0** [comment]
On my device i set false because I don't have Minecraft premium

**Comment by AlexProgrammerDE** [comment]
@Matikoo0 I am very confused. There is no Minecraft premium account. You need to set it to true and then to connect via the Minecraft Java edition on your computer.

**Comment by AlexProgrammerDE** [comment]
@Matikoo0 do you figure it out with my instructions? It´s been now two days.

**Comment by AlexProgrammerDE** [comment]
You said me you deactivated the online mode by hand and you are telling me that it gives you an error? I am extremly confused. Closing
