### ISSUE TITLE
Can't login into scp server on balena base image

### ISSUE THREAD

**Issue by Juxz** [AlexProgrammerDE/balena-minecraft-server#10]
Hi,

I wanted to use a Balena image instead of ubuntu for scp container :

Instead of :
- FROM ubuntu:16.04
I use :
- FROM balenalib/%%BALENA_MACHINE_NAME%%:latest

Then my attempts were always rejected and I think found the root cause. I had to change :

sed -i 's/PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config

To this

sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/g' /etc/ssh/sshd_config

It works like a charm now. Do you want a PR?

**Comment by AlexProgrammerDE** [comment]
@Juxz thanks. I didn´t know how to resolve this issue while coding so i left it like that. 👍 You can open the PR. It works great now. 😄
