### ISSUE TITLE
[BUG] HELPPPP

### ISSUE THREAD

**Issue by JacoVanR** [AlexProgrammerDE/balena-minecraft-server#100]
I changed my mojang name and all my progress is gone!!!!!!!

**Comment by AlexProgrammerDE** [comment]
@JacoVanR thats not really related to this project, but lets see. That only happens on online Mode false servers. Also called offline servers. Thats not really a issue to this project, but to how minecraft itself works.

**Comment by JacoVanR** [comment]
thx
