### ISSUE TITLE
Logs

### ISSUE THREAD

**Issue by JacoVanR** [AlexProgrammerDE/balena-minecraft-server#101]
Hi There! 
This server is GREAT!]
but the logs have a problem 
its this:

17.02.21 21:22:27 (+0100)  wifi-connect  Skipping setting up Wifi-Connect Access Point. Will check again in 120 seconds
17.02.21 21:24:27 (+0100)  wifi-connect  Checking internet connectivity ...
17.02.21 21:24:27 (+0100)  wifi-connect  Your device is already connected to the internet.
17.02.21 21:24:27 (+0100)  wifi-connect  Skipping setting up Wifi-Connect Access Point. Will check again in 120 seconds

That plays on loop the wole time! 
How do you make it stop?

**Comment by AlexProgrammerDE** [comment]
> 
> 
> Hi There!
> This server is GREAT!]
> but the logs have a problem
> its this:
> 
> 17.02.21 21:22:27 (+0100) wifi-connect Skipping setting up Wifi-Connect Access Point. Will check again in 120 seconds
> 17.02.21 21:24:27 (+0100) wifi-connect Checking internet connectivity ...
> 17.02.21 21:24:27 (+0100) wifi-connect Your device is already connected to the internet.
> 17.02.21 21:24:27 (+0100) wifi-connect Skipping setting up Wifi-Connect Access Point. Will check again in 120 seconds
> 
> That plays on loop the wole time!
> How do you make it stop?

It is not an issue. It's the Wi-Fi connect container which checks for Wi-Fi and if it has no Wi-Fi it opens one and asks you to connect it to another networks. It's not an issue, but just a log.
