### ISSUE TITLE
Unable to Connect to World

### ISSUE THREAD

**Issue by mhoromanski** [AlexProgrammerDE/balena-minecraft-server#104]
When trying to connect to the minecraft server locally I keep getting an error that says unable to connect to world? I'm certain I'm doing something wrong and its probably something stupid. Does this server only work with the java version of minecraft?

**Comment by AlexProgrammerDE** [comment]
@mhoromanski what does it say specificly?

**Comment by hasan0610** [comment]
Did u check the server ip it should be balenaminecraftserver.local
Unless u changed it with the environmental variable DEVICE_HOSTNAME
Also another thing to check is the bale a logs read through them they really help with troubleshooting

**Comment by AlexProgrammerDE** [comment]
No response 🤷🏻‍♂️
