### ISSUE TITLE
Magma.jar

### ISSUE THREAD

**Issue by MiniGPT** [AlexProgrammerDE/balena-minecraft-server#105]
Hello, im trying to start a magma server in 1.12.2, and when i start the server i have this error:

 mc-server  Setting device hostname to: balenaminecraftserver
 mc-server  
 mc-server  
 mc-server  Starting balenaMinecraftServer...
 mc-server  
 mc-server  Config already copied
 mc-server  Checking server JAR... Found a valid server file. It's called: minecraft_server.1.12.2.jar
 mc-server  paper.jar. Use ENABLE_UPDATE to update.
 mc-server  Starting JAR file with: 1G of RAM
 mc-server  Starting Magma
 mc-server  net.minecraftforge.fml.relauncher.ServerLaunchWrapper$JavaToNewException
 mc-server      at net.minecraftforge.fml.relauncher.ServerLaunchWrapper.main(ServerLaunchWrapper.java:45)
 mc-server  Magma Only Support's Java 8

How can i change the java version?

**Comment by AlexProgrammerDE** [comment]
Resolved in discord dms.
