### ISSUE TITLE
[BUG] geyser floodgate not working

### ISSUE THREAD

**Issue by hasan0610** [AlexProgrammerDE/balena-minecraft-server#106]
the plugins geyser and floodgate do not work it keeps saying 
java.net.UnknownHostException: auto
when trying to join
the plugin is at 
https://geysermc.org/

**Comment by Will-bit-tech** [comment]
Found the fix. What you have to do is use win scp and navigate to /serverfiles/plugins/Geyser-Spigot/config.yml and change address from auto to 127.0.0.1

**Comment by hasan0610** [comment]
Thank u working now also just a little question every time I open the server in the logs it keeps saying
<mc-server> >....
[00:03:46 WARN]: Unable to determine local host IP, please set server-ip in server.properties

**Comment by Will-bit-tech** [comment]
Go into /serverfiles/server.properties and remove the line server-ip=

**Comment by hasan0610** [comment]
Thx again rockbacon and another question does geyser work with dons becuz the server is working with no ip ddns so will geyser run over the ddns becuz I mainly use bedrock edition on the go and Java when I’m at home

**Comment by Will-bit-tech** [comment]
You need to port forward the bedrock ip on your docker-compose.yml and on your router for you to be able to play bedrock outside your network.

**Comment by hasan0610** [comment]
How do u do that

**Comment by hasan0610** [comment]
Can u like make a small tutorial for me

**Comment by hasan0610** [comment]
Also will the port be 25545

**Comment by hasan0610** [comment]
Do I use no ip for the docker-compose.yml

**Comment by Will-bit-tech** [comment]
1.Clone this repository onto a place on your hard drive. 

2.In the docker-compose.yml file look for the mc-server section. Under ports on a new line add this -"1932:1932/udp"
and on another new line add -"1932:1932/tcp" This basically maps the port of the docker container to the physical device. 
Should look something like this:
![Should look like this](https://user-images.githubusercontent.com/58570245/109163398-34749f00-7771-11eb-816e-c5ce658743c6.png)

3. Now download the cli from https://github.com/balena-io/balena-cli/blob/master/INSTALL.md

4. Now open a cmd window in the folder where the docker-compose.yml file is located and enter: balena push and then the name of your balena project. 
![CMD](https://user-images.githubusercontent.com/58570245/109165844-f167fb00-7773-11eb-8fcc-bcd858c26017.png)
![Project Name](https://user-images.githubusercontent.com/58570245/109164843-c92bcc80-7772-11eb-96cf-f909aef87625.png)

5.Once this is pushed you should get a unicorn in your command prompt window if everything went well. This should then update your raspberry pi automatically.

6.Finaly make sure to port forward port 1932 on your router so you can access your server outside your network!!!

**Comment by hasan0610** [comment]
thx alot its working now
