### ISSUE TITLE
@chazzytho  can you please delete the paper.jar file over SCP and the restart the Pi?

### ISSUE THREAD

**Issue by demm174** [AlexProgrammerDE/balena-minecraft-server#109]
@chazzytho  can you please delete the paper.jar file over SCP and the restart the Pi?

_Originally posted by @AlexProgrammerDE in https://github.com/AlexProgrammerDE/balena-minecraft-server/issues/16#issuecomment-606124100_

I followed all steps and it still doesn't work, added variable ENABLE_UPDATE and set it up to true, removed paper.jar file over SCP and now there is another problem:"Error: Unable to access jarfile paper.jar"

**Comment by hasan0610** [comment]
U should try deleting it from the micro sad card

**Comment by demm174** [comment]
I didn't find it on sd card but it was over SCP

**Comment by hasan0610** [comment]
Found the fix.  Delete paper and then replace with whatever .jar file then
reboot

**Comment by demm174** [comment]
where can I install a .jar file?

**Comment by hasan0610** [comment]
Seriously 
Ok so Minecraft servers can run many types of server softwares paper is one of the most popular vanilla is also popular these server softwares come in the form of .jar files u need them for the server to work
There is no point in deleting paper cuz it has a lot of plug-in support and is the most efficient

**Comment by demm174** [comment]
Thank you so much, I fixed it

**Comment by hasan0610** [comment]
No probs

**Comment by AlexProgrammerDE** [comment]
Ok as it is fixed I will just close this issue.
