### ISSUE TITLE
[BUG] to much ram and cpu usage when idle

### ISSUE THREAD

**Issue by hasan0610** [AlexProgrammerDE/balena-minecraft-server#110]
The server is taking about 5gb of ram when idle but as soon as u start playing the ram goes gown to like 1gb
 #![90860DA0-53C2-4F3C-A4A9-295461F2B0DD](https://user-images.githubusercontent.com/37555191/109307213-45bfb900-780e-11eb-9d40-3eeeccd45cc9.jpeg)
  #@![8B619E91-961C-4D72-98CA-6813F110A228](https://user-images.githubusercontent.com/37555191/109307241-5112e480-780e-11eb-8851-21139e1aad3d.jpeg)

**Comment by hasan0610** [comment]
Ok this is not funny look at this
![3498D66D-5FAB-4D42-8B14-D260AC24E4F8](https://user-images.githubusercontent.com/37555191/109541321-af9bc500-7a91-11eb-8b1b-15c52dbdedab.jpeg)

**Comment by AlexProgrammerDE** [comment]
How many plugins are you using? Is it lagging? Does it say the Pi is overloaded? It may be because of how java allocates memory.

**Comment by hasan0610** [comment]
I have only 1 plug-in geyser Mac

**Comment by AlexProgrammerDE** [comment]
Ok that sounds alright. How much did you set in the RAM variable? 8G?

**Comment by hasan0610** [comment]
6gb
