### ISSUE TITLE
[FEATURE]able to change recon password 

### ISSUE THREAD

**Issue by hasan0610** [AlexProgrammerDE/balena-minecraft-server#111]
Is there a wat to change the password rcon

**Comment by AlexProgrammerDE** [comment]
> 
> 
> Is there a wat to change the password rcon

You can change it. Edit the server.properties file in the serverfiles folder. You can do it as explained in the connect to files section. You will find an option such as rcon password somewhere in there. Here is a link to where we set it in the file: https://github.com/AlexProgrammerDE/balena-minecraft-server/blob/684f2455651a4d1fe0913ec5ce675428c1faa665/mc-server/serverfiles/server.properties#L39

**Comment by hasan0610** [comment]
Ok yea I’ll try that
