### ISSUE TITLE
Public IP address of balenacloud doesn't work

### ISSUE THREAD

**Issue by demm174** [AlexProgrammerDE/balena-minecraft-server#112]
I recently created a minecraft server for me and my friends, I did everything according to Alex's tutorial including port forwarding, I did a dynamic ip with noip, I have a new router and i believe that on raspberry pi 4 there is not firewall that can get in the way of port forwarding, the local ip works, the public ip doesn't work for anyone I have really done everything but without finding a solution.

**Comment by hasan0610** [comment]
Ok so u have to setup port forwarding in order to work does not matter on new router

**Comment by AlexProgrammerDE** [comment]
@demm174 can you show us how you forwarded your port? Is it 25565 and TCP?

**Comment by AlexProgrammerDE** [comment]
Going to close this due to inactivity.
