### ISSUE TITLE
Version not changing[BUG]

### ISSUE THREAD

**Issue by UnderRTX** [AlexProgrammerDE/balena-minecraft-server#116]
I am doing a project of BALENA with a raspberry pi4 model B 8GB, but when I change the paper.jar to magma (with WinSCP) it says that paper doesn't work and it download it again. Somebody can help me?

**Comment by ARamlall** [comment]
@UnderRTX  Hey so at least on my end if you change the paper.jar it tries to pull the correct paper file. My way of getting around that was to replace the file, just call it paper.jar also and use powershell to get the file hash and place the new file hash in the paper sha 256 file.

**Comment by UnderRTX** [comment]
The bug is solved, I entered a command that runs a custom jar and now it's
working fine. Thanks for your help.
