### ISSUE TITLE
[FEATURE] FTB Revelations

### ISSUE THREAD

**Issue by Domination987** [AlexProgrammerDE/balena-minecraft-server#117]
Would it be possible for you to make a easy and ready to go moded minecraft server with the mod pack FTB (feed the beast) relevations version 3.2.0    Me and my friends have been wanting to have our pi be a server for the moded minecraft but we are unsure how to actually get and start up a modded minecraft server on our 8gb pi4. Would you be able to set it up so we could just download it and image the os with the stuff or even make a turtorial on yt or here. I beg you please help me!

**Comment by ARamlall** [comment]
Hey @Domination987 . If you want to try its pretty simple. Download forge or fabric whichever is needed and run it on your local machine so you know what it looks like when it is running properly. Replace the paper.jar with the forge/fabric file and rename it to paper.jar for simplicity so the application does not get confused. Then you need to get the new hash for the new paper in which case you can use windows powershell and then place the new hash in the paper sha 256 file. After that restart your server so it starts to generate the new files needed. You then need to pull the mods and configs used and place them into the corresponding folders on the server. One more restart should make that into whatever pack server you want, just remember to keep it updated. 

My way may be a bit complicated at first but once you understand it becomes a bit more simple to maintain. If anyone else has a simpler way it would be nice to learn more about it.

**Comment by Domination987** [comment]
@ARamlall thanks for the help but unfortunately we returned the raspberry pi because its cpu could not run the server without lagging, so we are just going to buy a server instead. Thanks for the help though, this is a PSA for everyone who is thinking ab mods with the pi. It will not work well if you have more than two friends and even regular vanilla was super laggy. I would just buy a server online.

**Comment by ARamlall** [comment]
This is true, there is alot of server side lag with it but this should be expected especially if you are running a modpack with it. I use my pi to test out the modpack updates before I push it to the released server.
