### ISSUE TITLE
[BUG] Log time out of sync

### ISSUE THREAD

**Issue by ARamlall** [AlexProgrammerDE/balena-minecraft-server#120]
**Describe the bug**
The balena server itself has the time synced but the minecraft application is showing as four hours ahead causing a Incorrect Header Check error when attempting to log on to the server.

**Raspberry Pi 4 8gb**
 - balenaOS 2.71.3+rev1
 - SUPERVISOR VERSION 12.3.5
 
**Minecraft (please complete the following information):**
Windows, forge server (Invicta 1)

**Additional context**
It may be possible to fix if ntp is used but i doubt it becasue the balena server is running at the correct time but minecraft server is four hours ahead

Here is an example

01.04.21 **00:38:48** (-0400)  mc-server  **[04:38:48]** 
                                                                      
     ^ correct time(balena)            ^incorrect time (MC)    ?               

Edit:
I noticed this happened to all my balena mc servers. Unsure if it has always been this way now but something changed automatically causing users to be unable to connect. This is not a problem on servers that are not hosted on the balena platform.   

It is also a coincidence that i took one that shows a correct time at -0, other servers have -4 but show as 7 hours ahead in time.

Edit 2:
I attempted to reinstall the server from both a backup and scratch which did not work. After reinstalling balina with the mincraft deploy the problem is resolved, it seems to be a issue with servers that have been running for a while. Im going to keep looking into it but this is confusing me now.

**Comment by AlexProgrammerDE** [comment]
I assume somehow timezones are messed up? I will look into this if I find some time.
