### ISSUE TITLE
[FEATURE] Built in openjdk 8

### ISSUE THREAD

**Issue by ARamlall** [AlexProgrammerDE/balena-minecraft-server#123]
For simplicity have jdk 11 installed as default but also have the option to use jdk 8 with sudo update-alternatives --config java. Some mods are not compatible with 11 so having 8 as a alt would not hurt. 

Edit 1,
to be more clear instead of having the option in the dockerfile  of the mc-server have it installed and listed under update-alternatives. Have java 11 as default and 8 as a version that is not used until the user can ssh in or use the terminal to enable it.

**Comment by AlexProgrammerDE** [comment]
The problem with that is that 1. docker images would get large if we install both and 2. Docker images reset after a restart and only volumes (with for example the mc server data) get kept. I would prefer to not install java 8 or 11 on each restart and so the dockerfile approach is the best one in my eyes. I will close this issue for now. If you have an idea for another better solution feel free to reopen.
