### ISSUE TITLE
Problem with FTP

### ISSUE THREAD

**Issue by ViraajRandhawa** [AlexProgrammerDE/balena-minecraft-server#130]
the hostname 'balenaminecraftserver' isnt working on filezilla or any other FTP service please help.

**Comment by AlexProgrammerDE** [comment]
Please try SFTP instead of FTP. There is no FTP server running on the Pi.

**Comment by ViraajRandhawa** [comment]
> Please try SFTP instead of FTP. There is no FTP server running on the Pi.

I tried but it still did not work

**Comment by AlexProgrammerDE** [comment]
Could you please provide more info?

**Comment by ViraajRandhawa** [comment]
> Could you please provide more info?

ok so what’s happening is that when I use ‘balenaminecraftserver’ as a host anywhere, it tells me that the hostname doesn’t exist or is incorrect. But when I use the IP address it says ‘connection timed out’ after 20 seconds

**Comment by AlexProgrammerDE** [comment]
What software are you using and are you in the same network as the raspberry pi?

**Comment by ViraajRandhawa** [comment]
> What software are you using and are you in the same network as the raspberry pi?

I’m on the same network and I am using filezilla from a MacOS

**Comment by AlexProgrammerDE** [comment]
Did you select sftp in the settings before connecting? You would have to add it to your serverlist inside Filezilla and select sftp instead of ftp as a connection method. As said above the Pi doesn't host a ftp server and requires **ssh ftp** instead.

**Comment by ViraajRandhawa** [comment]
> Did you select sftp in the settings before connecting? You would have to add it to your serverlist inside Filezilla and select sftp instead of ftp as a connection method. As said above the Pi doesn't host a ftp server and requires **ssh ftp** instead.

I selected SFTP but like I said, it still told me the host name is incorrect

**Comment by ViraajRandhawa** [comment]
> Did you select sftp in the settings before connecting? You would have to add it to your serverlist inside Filezilla and select sftp instead of ftp as a connection method. As said above the Pi doesn't host a ftp server and requires **ssh ftp** instead.

here is what error Im getting now 
![Screenshot 2021-05-21 at 12 33 07 PM](https://user-images.githubusercontent.com/62015795/119096807-ab000080-ba31-11eb-9b44-de15269da4ac.png)

**Comment by AlexProgrammerDE** [comment]
Try `balenaminecraftserver.local` instead.

**Comment by ViraajRandhawa** [comment]
> Try `balenaminecraftserver.local` instead.
> Also please close port 22. Its a very bad idea to keep that port open.

I closed the port thank you. But I'm still getting the same error

**Comment by AlexProgrammerDE** [comment]
Maybe this could help: https://stackoverflow.com/a/40754476/12871087
I am kind of unsure if your Mac even picks up the pi. Maybe also try the pis **internal** ip instead of `balenaminecraftserver`.

**Comment by ViraajRandhawa** [comment]
> Maybe this could help: https://stackoverflow.com/a/40754476/12871087
> I am kind of unsure if your Mac even picks up the pi. Maybe also try the pis **internal** ip instead of `balenaminecraftserver`.

I got an inactivity error this time by using the pi's internal IP address

![Screenshot 2021-05-21 at 1 13 51 PM](https://user-images.githubusercontent.com/62015795/119101246-65920200-ba36-11eb-80a7-5cbda1f74d70.png)

**Comment by ViraajRandhawa** [comment]
Should I try to connect my pi to my laptop through a wire and try to use `balenaminecraftserver.local`?

**Comment by ViraajRandhawa** [comment]
I fixed the error (just needed to run Raspbian on my raspberry pi once)
