### ISSUE TITLE
Update to 1.17

### ISSUE THREAD

**Issue by random1748** [AlexProgrammerDE/balena-minecraft-server#135]
when I try to run the Mojang vanilla 1.17 jar I get this error
 java.lang.UnsupportedClassVersionError: net/minecraft/server/Main has been compiled by a more recent version of the Java Runtime (class file version 60.0), this version of the Java Runtime only recognizes class file versions up to 55.0
Can someone help me update the version of the jre to 60

**Comment by taedium8vitae** [comment]
It's because for 1.17, the minimum requirement is java 16 and not 11 like in 1.16. So we need to wait for the devs to update it...

**Comment by AlexProgrammerDE** [comment]
Bad news. Balena doesn't have java 16 prebuikt docker images. I will ask on their forums on if they could provide those.

**Comment by PeakMars** [comment]
Keep us updated! Tysm :D

**Comment by droptic** [comment]
Hello
any news about this?
Do you know if there is a way to do the manual update?
Regards

**Comment by KozmikNano** [comment]
@droptic you can use this for now. It works perfectly for me. https://github.com/AlexProgrammerDE/balena-minecraft-server/pull/137

**Comment by AlexProgrammerDE** [comment]
Java 16 is now included in the main repo. I guess I can close this now. Just push again to your fleet using the balena cli, and it should hopefully work again.
