### ISSUE TITLE
List The SSH Credentials 

### ISSUE THREAD

**Issue by swanserquack** [AlexProgrammerDE/balena-minecraft-server#136]
The reason I want this to be added because since I reimaged my SD I can't remember the ssh credentials which you use to log in to it. I'm sure some of the other people who want to add firewalls e.t.c cant because it doesn't list the credentials.

On the [webpace](https://www.balena.io/blog/how-to-create-a-minecraft-server-for-the-pi-4-with-balena/) I would like for you or someone else to add the default SSH credentials. If you can't do that then maybe try writing it to say the creds in the balena log on the dashboard.

Sorry if I sound a bit annoying and demanding but it is just really annoying.
Thanks in advance.

**Comment by MiniGPT** [comment]
The default SSH credentials are in the website i think:

"You can connect to the server and change your serverfiles. I recommend using a tool like WinSCP, or if you are using OSX or a linux distribution, you can use Filezilla. The IP Address to connect to is “balenaminecraftserver” (without the quotes), the protocol to choose is SCP (if you have the choice), the port number is 22, the username is “root” (again, without the quotes), and the password is “balenaserver” (no quotes). The files are in the folder named “serverfiles” at the root directory. You can double click to open that directory and browse the files in there."

**Comment by swanserquack** [comment]
> The default SSH credentials are in the website i think:
> 
> "You can connect to the server and change your serverfiles. I recommend using a tool like WinSCP, or if you are using OSX or a linux distribution, you can use Filezilla. The IP Address to connect to is “balenaminecraftserver” (without the quotes), the protocol to choose is SCP (if you have the choice), the port number is 22, the username is “root” (again, without the quotes), and the password is “balenaserver” (no quotes). The files are in the folder named “serverfiles” at the root directory. You can double click to open that directory and browse the files in there."

While yes these are the right credentials they only state its for the SCP server and when you first make the project there are updates to do (apt update & & apt upgrade) and you can only run those commands in a ssh session. You can't run those in the Web shell either.

**Comment by AlexProgrammerDE** [comment]
Commands like apt upgrade and apt update don't work inside docker containers. On every container restart, all non-permanent data will be erased and reset. Also, SCP uses SSH as its connection method, so you should be able to create a ssh session using these credentials.
