### ISSUE TITLE
Java 16

### ISSUE THREAD

**Issue by MiniGPT** [AlexProgrammerDE/balena-minecraft-server#138]
Hello, can we update to Java 16 with the terminal? OpenJDK already has java 16 but i don't think we can run commands on the terminal.

**Comment by AlexProgrammerDE** [comment]
Java 16 is now deployed to the fleet and committed to the repository. Let me know if it works for you.

**Comment by PBahner** [comment]
> Java 16 is now deployed to the fleet and committed to the repository. Let me know if it works for you.

How can I update to this Java Version? I've already updated to the newest balena os and still getting: 
` Minecraft 1.17 requires running the server with Java 16 or above. Download Java 16 (or above) from https://adoptopenjdk.net/`
