### ISSUE TITLE
[BUG] No Plug-in folder.

### ISSUE THREAD

**Issue by KozmikNano** [AlexProgrammerDE/balena-minecraft-server#139]
No plugin folder appears when using the server. I am using the pr version that allows me to use the 1.17 as my server.
I am using Scp to access the files and I am looking at the server files folder

**Comment by KozmikNano** [comment]
Figured out why this was happening. Since I was using the pr for 1.17 support it was grabbing the official Minecraft jar file.

**Comment by AlexProgrammerDE** [comment]
You can now use the code from the main repository. I pushed a fix for java temporarily.
