### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by SirCen** [AlexProgrammerDE/balena-minecraft-server#144]
Pushing the new build to the remote to update java to java 16 to get ready for 1.17, causes this error: 
"[Error]         Some services failed to build:
[Error]           Service: mc-server
[Error]             Error: The command '/bin/sh -c tar -zxf /opt/openjdk-16.0.1_linux-aarch64_bin.tar.gz -C /opt/' returned a non-zero code: 2
"
Hence the build fails. 
Is there a fix for this?

**Comment by AlexProgrammerDE** [comment]
@SirCen Should be fixed now. Let me know if it works.

**Comment by SirCen** [comment]
yep that works now!

**Comment by PeakMars** [comment]
Yep!
Thanks so much!

**Comment by sumwhat1** [comment]
Mine just stuck at 'build in progress'

Any ideas?

**Comment by PeakMars** [comment]
Update balenaos version first

**Comment by Petrullica** [comment]
Could someone please share a guide on how to update to Java 16?
I tried to follow the guide in the PaperDocs site without success.

**Comment by KozmikNano** [comment]
I would just save/backup the important files like: usercache, world, whitlist, bans, server.properties, etc. And reinstall with the newer version. Once that is don reimport the files you saved earlier.

**Comment by Bmartin3k** [comment]
OK, I'm very new at this, how do I push the new build down...

**Comment by KozmikNano** [comment]
> OK, I'm very new at this, how do I push the new build down...

Did you backup the important files? If yes then please reply. If you have no idea how to do that then please reply. Sorry if this comes out rude I’m just trying to make sure you have everything set up properly that way you don’t lose any data.

**Comment by Bmartin3k** [comment]
> > OK, I'm very new at this, how do I push the new build down...
> 
> Did you backup the important files? If yes then please reply. If you have no idea how to do that then please reply. Sorry if this comes out rude I’m just trying to make sure you have everything set up properly that way you don’t lose any data.

Yes, I have everything backedup

**Comment by KozmikNano** [comment]
Alr

> > > OK, I'm very new at this, how do I push the new build down...
> > 
> > 
> > Did you backup the important files? If yes then please reply. If you have no idea how to do that then please reply. Sorry if this comes out rude I’m just trying to make sure you have everything set up properly that way you don’t lose any data.
> 
> Yes, I have everything backedup

Alright cool. Now do you have your server setup with multiple programs other than the Minecraft server ones? If you need more clarification please let me know.

**Comment by Bmartin3k** [comment]
> Alr
> 
> > > > OK, I'm very new at this, how do I push the new build down...
> > > 
> > > 
> > > Did you backup the important files? If yes then please reply. If you have no idea how to do that then please reply. Sorry if this comes out rude I’m just trying to make sure you have everything set up properly that way you don’t lose any data.
> > 
> > 
> > Yes, I have everything backedup
> 
> Alright cool. Now do you have your server setup with multiple programs other than the Minecraft server ones? If you need more clarification please let me know.

No. I've tried rerunning etcher but the build it has is the same one I had on it. And I've tried updating java but it just reverts back to java 11. So I wasn't sure what I was doing wrong

**Comment by KozmikNano** [comment]
There are two options, reflash your pi, or publish it yourself. Witch one do you want to use?

**Comment by Bmartin3k** [comment]
> There are two options, reflash your pi, or publish it yourself. Witch one do you want to use?

I've reflashed my pi but it just downloads balenaminecraftserver, then downloads paper 1.17.1, then says I need to update java to 16.

**Comment by KozmikNano** [comment]
Well I guess we should try the manual install for now. First set up Balena ClI

**Comment by Bmartin3k** [comment]
> 
> 
> Well I guess we should try the manual install for now. First set up Balena ClI https://github.com/balena-io/balena-cli

done

**Comment by KozmikNano** [comment]
Nice, now open either the terminal(for Linux) or Powershell as a administrator (for windows). Then type 
```balena login```

**Comment by Bmartin3k** [comment]
> 
> 
> Nice, now open either the terminal(for Linux) or Powershell as a administrator (for windows). Then type
> `balena login` Please login by following the steps on there

done

**Comment by KozmikNano** [comment]
> > Nice, now open either the terminal(for Linux) or Powershell as a administrator (for windows). Then type
> > `balena login` Please login by following the steps on there
> 
> done

You can now close the powershell and download the zip file for this repo (On the home page of this repo there should be a green button with the word code on it. Click it then click download zip.) Once downloaded extract it to a folder.

**Comment by Bmartin3k** [comment]
> 
> 
> > > Nice, now open either the terminal(for Linux) or Powershell as a administrator (for windows). Then type
> > > `balena login` Please login by following the steps on there
> > 
> > 
> > done
> 
> You can now close the powershell and download the zip file for this repo (On the home page of this repo there should be a green button with the word code on it. Click it then click download zip.) Once downloaded extract it to a folder.

done

**Comment by KozmikNano** [comment]
> done

You can now enter the folder until you get the contents of it looking like those of the code on the main page. (So many folders and files not just one folder.)

**Comment by Bmartin3k** [comment]
> 
> 
> > done
> 
> You can now enter the folder until you get the contents of it looking like those of the code on the main page. (So many folders and files not just one folder.)

alright

**Comment by KozmikNano** [comment]
This may be a little confusing but you have to (on windows) click on the blue file button (top left) 
![0E420296-48EB-4D80-82CE-97A0081354B1](https://user-images.githubusercontent.com/77017394/124876859-78d24000-df98-11eb-911d-9a0d63497118.jpeg). Then hover over the powershell option and select open as administrator.

**Comment by Bmartin3k** [comment]
> 
> 
> This may be a little confusing but you have to (on windows) click on the blue file button (top left)
> ![0E420296-48EB-4D80-82CE-97A0081354B1](https://user-images.githubusercontent.com/77017394/124876859-78d24000-df98-11eb-911d-9a0d63497118.jpeg) Then hover over the powershell option and select open as administrator.

None of this is confusing. I actually work in IT but I'm hardware/networking. I just have little experience with this side

**Comment by KozmikNano** [comment]
> > This may be a little confusing but you have to (on windows) click on the blue file button (top left)
> > ![0E420296-48EB-4D80-82CE-97A0081354B1](https://user-images.githubusercontent.com/77017394/124876859-78d24000-df98-11eb-911d-9a0d63497118.jpeg) Then hover over the powershell option and select open as administrator.
> 
> None of this is confusing. I actually work in IT but I'm hardware/networking. I just have little experience with this side

Ok good to know. Now you just have to type ```balena push “your application name”``` without the quotes. You can find the name of your application by looking here 
![2A5161A7-46A1-418D-918B-F5A5E002B6AC](https://user-images.githubusercontent.com/77017394/124877917-8fc56200-df99-11eb-8fb6-517760d822f6.jpeg)

**Comment by KozmikNano** [comment]
By the time this is done you should see a unicorn in the powershell

**Comment by Bmartin3k** [comment]
> 
> 
> By the time this is done you should see a unicorn in the powershell

it says application is ambiguous

**Comment by KozmikNano** [comment]
> > By the time this is done you should see a unicorn in the powershell
> 
> it says application is ambiguous

True, did it by any chance Finnish or is it still working?

**Comment by Bmartin3k** [comment]
![Screenshot 2021-07-08 021739](https://user-images.githubusercontent.com/67239149/124879343-be8c0a00-df92-11eb-8825-5f9b1a1d590a.png)

**Comment by KozmikNano** [comment]
Oh, did know that was a thing. Let me look for a fix.

**Comment by KozmikNano** [comment]
would you mind typing ```balena apps```?

**Comment by Bmartin3k** [comment]
> 
> 
> would you mind typing `balena apps`? What is the result?

i fixed it, i used "balena push username/balena-minecraft-server"

**Comment by KozmikNano** [comment]
> 
> 
> > would you mind typing `balena apps`? What is the result?
> 
> i fixed it, i used "balena push username/balena-minecraft-server"

Nice, weird you had to do that. I am assuming you have seen the unicorn by now. If so is the server finally working?

**Comment by Bmartin3k** [comment]
> 
> 
> > > would you mind typing `balena apps`? What is the result?
> > 
> > 
> > i fixed it, i used "balena push username/balena-minecraft-server"
> 
> Nice, weird you had to do that. I am assuming you have seen the unicorn by now. If so is the server finally working?

yup

**Comment by KozmikNano** [comment]
Nice, and no error about java? Just wanting to make sure I was good to go!

**Comment by Bmartin3k** [comment]
> 
> 
> Nice, and no error about java? Just wanting to make sure I was good to go!

i'm up and running. Thanks for the help. I think this gave me some good insight into how this all works as well.

**Comment by KozmikNano** [comment]
> > Nice, and no error about java? Just wanting to make sure I was good to go!
> 
> i'm up and running. Thanks for the help. I think this gave me some good insight into how this all works as well.

I am glad that I helped. If you need any help you know where to get me!
