### ISSUE TITLE
[BUG] raspberrypi3 16-jdk-buster not found

### ISSUE THREAD

**Issue by katanaaa** [AlexProgrammerDE/balena-minecraft-server#145]
Failing to build the image.

**To Reproduce**
1. Install Balena-cli tools
2. balena login
3. balena push mc_server

`[Info]          Uploading images\n`
`[Success]       Successfully uploaded images`
`[Error]         Some services failed to build:`
`[Error]           Service: mc-server`
`[Error]             Error: manifest for balenalib/raspberrypi3-debian-openjdk:16-jdk-buster not found: manifest unknown: manifest unknown`
`[Info]          Built on arm04`
`[Error]         Not deploying release.`
`Remote build failed`

**Raspberry Pi (please complete the following information):**
 - OS: [e.g. balenaOS 2.41.0+rev4]

**Minecraft**
 - Device:  Thinkpad t450s
 - OS: Manjaro Linux
 - Minecraft Edition [e.g. Java Edition]
 - Minecraft Version [e.g. 1.17.1]

**Comment by AlexProgrammerDE** [comment]
Thanks for reporting. I will open an issue on the balena base image repo. Btw you can not run this project on a raspberry pi 3. There is really not enough ram available on it to run a mc server.

**Comment by katanaaa** [comment]
> Thanks for reporting. I will open an issue on the balena base image repo. Btw you can not run this project on a raspberry pi 3. There is really not enough ram available on it to run a mc server.

thanks for fast reply, I  noticed that the PI3 ram isn't enough. I will upgrade to pi 4 once i can. very excited about this project
