### ISSUE TITLE
[ISSUE] Server keeps crashing

### ISSUE THREAD

**Issue by JustToasty** [AlexProgrammerDE/balena-minecraft-server#146]
**Describe the issue**
server keeps crashing a few minutes after it goes up
Plugins used: EssentialsX. EssentialsX Chat

**Raspberry Pi 4 2G:**
 - OS: [balenaOS 2.80.5+rev1]
 - Version [12.8.7]

**Minecraft Java Edition:**
 - Device: [PC]
 - OS: [Windows 10]
 - Minecraft Edition [Java Edition]
 - Minecraft Version [1.17.1]

Ive ran a server using this on 1.16 with the exact same plugins and it ran perfectly fine, im not sure why this one is having so many issues. Im also using the power supply that came with the case im using.

**Comment by ModeratelyDisappointing** [comment]
wrong pi model, 4 GB and up only

**Comment by AlexProgrammerDE** [comment]
This was probably due to an outdated java version. Please redeploy this application to get java 16.
