### ISSUE TITLE
[BUG] JDK 16 missing for Jetson Nano

### ISSUE THREAD

**Issue by mafrmt00** [AlexProgrammerDE/balena-minecraft-server#147]
**Describe the bug**
There is no JDK 16 for Jetson-Nano

**To Reproduce**
Build the default config and push it to a jetson-nano device.

**Expected behavior**
My Kids playing Minecraft together.

**Screenshots**
[Error]         Some services failed to build:
[Error]           Service: mc-server
[Error]             Error: manifest for balenalib/jetson-nano-debian-openjdk:16-jdk-buster not found: manifest unknown: manifest unknown
[Info]          Built on arm01
[Error]         Not deploying release.

**Additional context**
Switching to JDK 8 makes the image run on the device but produces the following error:
Minecraft 1.17 requires running the server with Java 16 or above. Download Java 16 (or above) from https://adoptopenjdk.net/

**Comment by AlexProgrammerDE** [comment]
I will forward this to the balena base image repository. Thanks for reporting!
