### ISSUE TITLE
How can i install forge in balena

### ISSUE THREAD

**Issue by widgb** [AlexProgrammerDE/balena-minecraft-server#15]
I have been trying quite a few ways to install the forge instead of the spigot but I cannot solve the problems it gives me: it does not find the file, it does not download ... If you could locate a file with forge I would really appreciate it. Thank you.

**Comment by AlexProgrammerDE** [comment]
@widgb i found the issue. This repo uses java 11. Old forge uses java 8. To fix this issue you have to downgrade the used image. You have to change the Dockerfile of the mc-server container. The file is in the mc-server directory. The first line is:
> FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-openjdk:latest-buster

You have to replace this line with:
> FROM balenalib/%%BALENA_MACHINE_NAME%%-debian-openjdk:8-jdk-stretch

This will fix the issue. Don´t forget to push the changed files via `balena push <appname>`.

**Comment by AlexProgrammerDE** [comment]
@widgb its been now 8 days. Feel free to reopen if you experience this issue again.

**Comment by widgb** [comment]
Sorry, the answer had not come to me, because the problem apart from that of java is also that the spigot is installed directly and I do not know how to install forge
