### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Ulyss1974** [AlexProgrammerDE/balena-minecraft-server#150]
**Describe the bug**

I've installed your project on my raspberry pi and it's not working.
First time I used the one click deployment and when I tried to log in to the server in Minecraft nothing hapend.  I've tried with different version of Minecraft and it changed nothing.
I've also unsed the manual deployment and it behaved the same way.
In my balena dashboard I can see that my device is online and I can see the logs in the scren but the server is not able to launch. See snapshot (a).

**To Reproduce**

1. One click and manual deployment.
2. In Minecraft click on multiplayer/direct connection
3. Used different server address: balenaminecraftserver - balenaminecraftserver.local - the IP address of my device
4. Failed to connect to the server in every case.  See snapshots (b-c-d).

**Expected behavior**
I would expect to play on the server.

**Screenshots**

(a)
<img width="767" alt="Capture d’écran 2021-07-25 111323" src="https://user-images.githubusercontent.com/87615993/126904816-a53989f1-a6a9-4caf-afb7-6a012140b626.png">

(b)
<img width="403" alt="Capture d’écran 2021-07-25 111710" src="https://user-images.githubusercontent.com/87615993/126904855-bb947ffa-e3f7-49ad-a411-d3f682ac3946.png">

(c)
<img width="394" alt="Capture d’écran 2021-07-25 111831" src="https://user-images.githubusercontent.com/87615993/126904861-0174370c-0142-446a-b187-7a4a9fe19e34.png">

(d)
<img width="386" alt="Capture d’écran 2021-07-25 112002" src="https://user-images.githubusercontent.com/87615993/126904869-76764e5d-8737-4404-b82d-767817b6303c.png">

**Raspberry Pi (please complete the following information):**
 - OS: balenaOS 2.80.5+rev1
 - Superviser Version 12.8.7

**Minecraft (please complete the following information):**
 - Device: PC
 - OS: Windows 10 Familly
 - Minecraft java
 - Minecraft Version 1.16.4 and 1.17.1

**Additional context**
No other context about the problem.

**Comment by AlexProgrammerDE** [comment]
@Ulyss1974 please set ENABLE_UPDATE to true to get a new jar file. That should hopefully download a working one.

**Comment by Ulyss1974** [comment]
Where should I do that?  Is it on a file on the devine or is it on the balena Dashboard?

**Comment by hasan0610** [comment]
this issue happened to me ik what to do
so first open winscp and connect to the pi then find the folder server files
then open it and look for paper.jar delete it then go to papermc.io
and downloud latest version then rename it to paper.jar nad replace it where the old one was and also set the ram to 7gb 8 gb is too much for just the server u have to leave some for other services

**Comment by Ulyss1974** [comment]
Thamk you @hasan0610 I managed to run my server.
