### ISSUE TITLE
[BUG]server refuses to update to jdk 16

### ISSUE THREAD

**Issue by random1748** [AlexProgrammerDE/balena-minecraft-server#152]
**Describe the bug**
my Minecraft server refuses to use JDK 16 after I one-click deploy and manually deployed the project.
It was running 1.16 for a while and going well but we wanted 1.17. I waited for it to be released and tried to update it.
I had an earlier issue with* all the detail if you are interested. should I wipe it and reinstall

**Comment by random1748** [comment]
I reset it and got  mc-server  Setting device hostname to: balenaminecraftserver
 mc-server  
 mc-server  
 mc-server  Starting balenaMinecraftServer...
 mc-server  
 mc-server  Forcing server update
 mc-server  Downloading 1.17.1 build 137...
 mc-server  Starting JAR file with: 2G of RAM
 mc-server  Minecraft 1.17 requires running the server with Java 16 or above. Download Java 16 (or above) from https://adoptopenjdk.net/
Service exited 'mc-server sha256:e520c8f017254e730a70dfbcd53302d9197b20022c583d527ea65b815ce83920'
Restarting service 'mc-server sha256:e520c8f017254e730a70dfbcd53302d9197b20022c583d527ea65b815ce83920'


even after redeploying a newly downloaded version of the project it still gave the same message

**Comment by AlexProgrammerDE** [comment]
@random1748 can you send me the dockefile.template file from the mc server folder in the copy of the repository you have made locally to deploy it using the balena CLI?

**Comment by AlexProgrammerDE** [comment]
Closing due to incativity.
