### ISSUE TITLE
Invalid or corrupt jarfile paper.jar [BUG]

### ISSUE THREAD

**Issue by chazzytho** [AlexProgrammerDE/balena-minecraft-server#16]
**Describe the bug**
The minecraft server was running without problem on a Pi 4GB with mods installed (Essentials). I changed one variable there over WinSCP and then the server stopped working, showing the error `Error: Invalid or corrupt jarfile paper.jar` on balenaCloud. This also happened when I fisrt set it up but was able to circumvent it by using the solution from a previously resolved issue ( setting `ENABLE_UPDATES` to `true` ).

**To Reproduce**
1. Change variable in mod
2. Reboot Pi (log attached)

**Expected behavior**
I expected the minecraft server to start up normally

**Raspberry Pi (please complete the following information):**
 - OS: [balenaOS 2.47.1+rev1]
 - Version [10.6.27]

**Minecraft (please complete the following information):**
 - Device: [PC]
 - OS: [Windows 10]
 - Minecraft Edition [Java Edition]
 - Minecraft Version [1.15.2]

**Additional context**
After typing this out, I might have realized the problem... Maybe the minecraft server wasn't properly shut down before messing with the variables via WinSCP, could this be the problem? If so, how could I fix this and save the server data?

`ENABLE_UPDATES` is still set to `true`

[minecraft_server_green-darkness-30.03.20_18_53_22_(+0200).txt](https://github.com/AlexProgrammerDE/balena-minecraft-server/files/4404301/minecraft_server_green-darkness-30.03.20_18_53_22_.%2B0200.txt)

**Comment by AlexProgrammerDE** [comment]
@chazzytho  can you please delete the paper.jar file over SCP and the restart the Pi.

**Comment by chazzytho** [comment]
@AlexProgrammerDE Thank you for the quick reply and support, it worked! I guess I messed it up by editing while it was running.

**Comment by Jonathanpou** [comment]
How do you delete the paper.jar file over SCP?

**Comment by AlexProgrammerDE** [comment]
> 
> 
> How do you delete the paper.jar file over SCP?

If using a client I guess just clicking it and click remove or right-clicking and remove?

**Comment by demm174** [comment]
what SCP stands for

**Comment by Jonathanpou** [comment]
> what SCP stands for?

Secure Copy Protocol

**Comment by demm174** [comment]
I must delete the paper.jar file but I don't know how to delete its

**Comment by Jonathanpou** [comment]
Have you tried the following?

![Skærmbillede 2021-02-25 kl  17 39 52](https://user-images.githubusercontent.com/34024791/109185628-7a8d2b00-7790-11eb-984b-d5ac00daf124.png)

**Comment by demm174** [comment]
i removed the file. Now there's the error: Unable to access farfile paper.jar

**Comment by Jonathanpou** [comment]
Have you set ENABLE_UPDATES  to true?

**Comment by demm174** [comment]
yes, i did

**Comment by demm174** [comment]
i resolved it at all, thanks

**Comment by demm174** [comment]
I removed it, restarted the PI and it still doesn't work

**Comment by Stewart-Michael-116** [comment]
> I removed it (paper.jar), restarted the PI and it still doesn't work
I have the exact same issue and process
