### ISSUE TITLE
change scp port

### ISSUE THREAD

**Issue by random1748** [AlexProgrammerDE/balena-minecraft-server#160]
I have 2 pi's and I want to have one on 21 and one on 22 so I can port forward both and SCP into them to add plugins and manage it. does anyone know how I could do that

**Comment by hasan0610** [comment]
u ont neeed to change the port cjust need to change the hostname

**Comment by taedium8vitae** [comment]
you just need to forward the ports to a different one for each pi, so you can differentiate them while connecting from the outside
nothing needs to be changed on the pis themselves, just on your router's config
