### ISSUE TITLE
[BUG] Invalid or corrupt jarfile paper.jar

### ISSUE THREAD

**Issue by mariusrueve** [AlexProgrammerDE/balena-minecraft-server#162]
**Describe the bug**
When the mc-server service tries to start the server, the message `Error: Invalid or corrupt jarfile paper.jar` appears

**To Reproduce**
Start a new server with the given instructions

**Screenshots**
![grafik](https://user-images.githubusercontent.com/44000950/133747348-335e7d80-273e-4d21-b4ad-7bcb9246ddf8.png)

**Raspberry Pi (please complete the following information):**
 - OS: balenaOS 2.83.10+rev1

**Comment by Nullcomputer** [comment]
I have the same problem

**Comment by DanWill7** [comment]
Anyone found a solution yet?

**Comment by AlexProgrammerDE** [comment]
@mariusrueve @DanWill7 this bug is caused by a missing internet connection while downloading the paper jar file. You should be able to get a working jar file by setting the `ENABLE_UPDATE` environment variable inside your dashboard to `true`.

**Comment by mariusrueve** [comment]
Thank you! 🙏🏼  I will test it, when the serever isn't used regularly
