### ISSUE TITLE
[BUG] balena-rcon Issue

### ISSUE THREAD

**Issue by tom7351** [AlexProgrammerDE/balena-minecraft-server#167]
**Describe the bug**
When trying to start a terminal session with balena rcon the rcon gives error 111 and that the connection was refused.

**To Reproduce**
I do not know how to reproduce this behavior

**Expected behavior**
A Rcon window should open to give me access to all the commands in minecraft.

**Screenshots**
![reeee](https://user-images.githubusercontent.com/80645318/134894450-13109892-2c89-4d86-a22a-3c8af13353b1.jpg)

**Raspberry Pi (please complete the following information):**
 - OS: balenaOS 2.65.0+rev2
 - Version ?

**Minecraft (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Minecraft Edition Java
 - Minecraft Version 1.17.1

**Comment by SPancerfaustyna** [comment]
Hey, I have a question, Do you have in server.properties "enable-rcon" set to True? If not change it. In my case this was my problem.

**Comment by tom7351** [comment]
> Hey, I have a question, Do you have in server.properties "enable-rcon" set to True? If not change it. In my case this was my problem.

Yes I have. It is only that balena-rcon doesn't work. mcrcon works. but the service doesn't work. even when i open a terminal via balena cloud and use mcrcon via that it does work

**Comment by TechnoTalksDev** [comment]
Yea it would be nice if you could just access the mc console from the dashboard because sometimes mcrcon just doesn't work.

**Comment by tom7351** [comment]
Issue fixed itself with re-deployment.
