### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by xaned41390** [AlexProgrammerDE/balena-minecraft-server#17]
I need to connect my raspberry to another network, but how to do it?

**Comment by xaned41390** [comment]
???

**Comment by AlexProgrammerDE** [comment]
@xaned41390 if your Pi finds not on boot the set wifi it will open a Wifi. If you then connect to this Wifi you will be prompted to put in the credentials of the new Wifi. The name is balenaMinecraftServer and the password balenaMinecraftServer.

**Comment by xaned41390** [comment]
Thanks
