### ISSUE TITLE
[BUG] Forge 1.17 does not come with a .jar file anymore

### ISSUE THREAD

**Issue by te-ce** [AlexProgrammerDE/balena-minecraft-server#171]
As seen [here](https://www.reddit.com/r/MinecraftForge/comments/pcast5/forge_1171_not_installing_the_server_jar_files/) forge server does not come with a .jar file anymore from 1.17 and up, but starts now via a .bat or .sh file. 
How do we start these files?

![files for forge server](https://preview.redd.it/46yz6q8t9sj71.png?width=1942&format=png&auto=webp&s=563c4ad104e72db40462dd02bcc4ff5391ffda69)

**Comment by AlexProgrammerDE** [comment]
![image](https://user-images.githubusercontent.com/40795980/140636222-8cf50e44-144f-47c8-bec5-e5ed943717c8.png)
the unix args text file seems to show what the new flags for java are. Will look into how we could add this into this project. Perhaps a custom start command?

**Comment by te-ce** [comment]
Hmm idk whats best suited here
