### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by FreshSoul** [AlexProgrammerDE/balena-minecraft-server#18]
Starting jar file with 2GB of RAM.
 Error: Invalid or corrupt jarfile paper.jar.
ENABLE_UPDATE to true didnt helped

**Comment by AlexProgrammerDE** [comment]
@FreshSoul can you please delete the file manually over SCP?

**Comment by FreshSoul** [comment]
paper.jar?

**Comment by AlexProgrammerDE** [comment]
@FreshSoul yes.

**Comment by FreshSoul** [comment]
Oh, thank you very much, its work
