### ISSUE TITLE
Dynmap

### ISSUE THREAD

**Issue by Bmartin3k** [AlexProgrammerDE/balena-minecraft-server#181]
Since the update with 1.18 and java 17 dynmap is failing to load, it is just a version issue?

**Comment by taedium8vitae** [comment]
Dynmap just hasn't updated to 1.18, if you want to use the beta (which is compatible) for the time being, you can [download it here](https://www.spigotmc.org/resources/dynmap.274/update?update=434113).

**Comment by AlexProgrammerDE** [comment]
Yeah you always need to wait for all other plugins to get updated aswell. Well answer was given already. Thanks taedium8vitae! Going to close the issue.
