### ISSUE TITLE
[BUG] 1.17 not starting

### ISSUE THREAD

**Issue by UnderRTX** [AlexProgrammerDE/balena-minecraft-server#183]
**Describe the bug**
When trying to start the 1.17.1 forge jar on a raspi 4B 8GB, this error shows in the log:

19.12.21 16:47:09 (+0100)  mc-server  Error: Invalid or corrupt jarfile run.bat

any ideas?

**Comment by UnderRTX** [comment]
Full error:

19.12.21 14:17:04 (+0100)  mc-server  Setting device hostname to: Rpi
19.12.21 14:17:04 (+0100)  mc-server  
19.12.21 14:17:04 (+0100)  mc-server  
19.12.21 14:17:04 (+0100)  mc-server  Starting balenaMinecraftServer...
19.12.21 14:17:04 (+0100)  mc-server  
19.12.21 14:17:04 (+0100)  mc-server  Config already copied
19.12.21 14:17:05 (+0100)  mc-server  Checking server JAR... Found a valid server file. It's called: 1.17.1.jar
19.12.21 14:17:05 (+0100)  mc-server  paper.jar. Use ENABLE_UPDATE to update.
19.12.21 14:17:05 (+0100)  mc-server  Starting JAR file with: 8G of RAM
19.12.21 14:17:05 (+0100)  mc-server  JVM info: Debian - 11.0.12 - 11.0.12+7-post-Debian-2deb10u1
19.12.21 14:17:05 (+0100)  mc-server  java.net.preferIPv4Stack=true
19.12.21 14:17:06 (+0100)  mc-server  Found java version 11.0.12
19.12.21 14:17:09 (+0100)  mc-server  Exception in thread "main" 
19.12.21 14:17:09 (+0100)  mc-server  java.awt.HeadlessException: 
19.12.21 14:17:09 (+0100)  mc-server  No X11 DISPLAY variable was set, but this program performed an operation which requires it.
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:208)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/java.awt.Window.<init>(Window.java:548)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/java.awt.Frame.<init>(Frame.java:423)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/java.awt.Frame.<init>(Frame.java:388)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/javax.swing.SwingUtilities$SharedOwnerFrame.<init>(SwingUtilities.java:1919)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/javax.swing.SwingUtilities.getSharedOwnerFrame(SwingUtilities.java:1995)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/javax.swing.JOptionPane.getRootFrame(JOptionPane.java:1689)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:868)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:670)
19.12.21 14:17:09 (+0100)  mc-server    at java.desktop/javax.swing.JOptionPane.showMessageDialog(JOptionPane.java:641)
19.12.21 14:17:09 (+0100)  mc-server    at net.minecraftforge.installer.SimpleInstaller.launchGui(SimpleInstaller.java:177)
19.12.21 14:17:09 (+0100)  mc-server    at net.minecraftforge.installer.SimpleInstaller.main(SimpleInstaller.java:147)


Can it be openjdk version? i have the latest on the Raspberry and it may be the 16th version, not the 17th

**Comment by AlexProgrammerDE** [comment]
Could you explain your setup more in detail? What environment files do you have and how does your server files folder look like via scp?

**Comment by UnderRTX** [comment]
Now I have the Jar_file set to run.sh because linux use them, but still got the error. Here are some images:

![winscp](https://user-images.githubusercontent.com/80577985/146691129-b3b2fe48-3705-4057-b808-b808768dc826.png)

![image](https://user-images.githubusercontent.com/80577985/146691166-3ef61a62-5575-40d2-b597-a891cd67e157.png)

**Comment by UnderRTX** [comment]
Wait isn't this the same issue as this one? https://github.com/AlexProgrammerDE/balena-minecraft-server/issues/171

**Comment by taedium8vitae** [comment]
No, this isn't the same issue because this other guy tried to use forge for his server.
Your issue has happened to me a few times and it isn't that bad, for me downloading [the latest paper jar](https://papermc.io/downloads), renaming it paper.jar and replacing the old on with the new one worked.
