### ISSUE TITLE
[Noob Approaching] How to update server?

### ISSUE THREAD

**Issue by Cicango** [AlexProgrammerDE/balena-minecraft-server#185]

**Comment by taedium8vitae** [comment]
The way I do it is I download [the latest paper build](https://papermc.io/downloads), connect to my server with [FileZilla](https://filezilla-project.org) and replace the old `paper.jar` file.
If you need more support on one of those tasks, reply directly under this post!

**Comment by AlexProgrammerDE** [comment]
quite easy. You have to set the environment variable `ENABLE_UPDATE` to `true` and it will download the latest paper build.
