### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by FreshSoul** [AlexProgrammerDE/balena-minecraft-server#19]
How to delete bungeecord?

**Comment by FreshSoul** [comment]
please @AlexProgrammerDE dont ignore

**Comment by AlexProgrammerDE** [comment]
@FreshSoul sorry i was busy. You want to delte bungeecord? But you dont have it.

**Comment by FreshSoul** [comment]
No no, im today installed it

**Comment by AlexProgrammerDE** [comment]
You have tried my others repository code?

**Comment by FreshSoul** [comment]
Yes

**Comment by AlexProgrammerDE** [comment]
But bungeecord is the main feature of the code. What do you want from me?

**Comment by FreshSoul** [comment]
I meant it https://github.com/AlexProgrammerDE/balena-minecraft-bungeecord

**Comment by AlexProgrammerDE** [comment]
So you want my code without bungeecord? But then is your Pi doing nothing.

**Comment by FreshSoul** [comment]
Hello, how to change rcon password?

**Comment by FreshSoul** [comment]
i changed it in file server.properties, but on balena cloud Authentication failed!

**Comment by AlexProgrammerDE** [comment]
@FreshSoul do you mean the rcon container?

**Comment by FreshSoul** [comment]
sure

**Comment by AlexProgrammerDE** [comment]
@FreshSoul the password should be `balena`. The rcon container trys to connect with the password `balena`. I still havent implemented a custom password feature.

**Comment by FreshSoul** [comment]
ok, thanks
