### ISSUE TITLE
[BUG] Migrate files to external HDD

### ISSUE THREAD

**Issue by MiloDoesStuff1** [AlexProgrammerDE/balena-minecraft-server#197]
**Describe the bug**
The server that I am running is booting and all of my files are on a micro SD card, with the SD card my server is thread dumping. I want to transfer my server to a HDD but I don't know how to. Since Balena Minecraft is not like other Minecraft server I don't know if I need to do something different then a normal paper server.

**Raspberry Pi (please complete the following information):**
 - OS: [e.g. balenaOS 2.99.27]

**Minecraft (please complete the following information):**
 - Device: [Raspberry PI 4 8 GB]
 - OS: [ BalenaOS]
 - Minecraft Edition [e.g. Java Edition]
 - Minecraft Version [1.19]

**Comment by AlexProgrammerDE** [comment]
I would not recommend moving anything to an external hard drive. Micro SD cards these days can have up to 256 GB of storage and are A LOT faster than HDD's. Why do you want to move it to a HDD?
