### ISSUE TITLE
[BUG] Plugins timing out.

### ISSUE THREAD

**Issue by ARamlall** [AlexProgrammerDE/balena-minecraft-server#198]
**Describe the bug**
After updating to the latest paper, also tried rolling back many plugins time out when the server is starting up. Here is an example from one of the plugins https://mcpaste.io/92f0167e3bd671f0. All look to have the same  java.base/sun.nio.ch.Net.connect0(Native Method) issue with java.net.ConnectException: Connection timed out as the reason.  Testing on a hosted server does not have the same issues with the exact same files

plugins include 
essentialsx
luckperms
multiverse core
placeholder API
bloblib
and more 

**To Reproduce**
Allow server to auto update to paper 1.19.2 # 138
start server
scp server spams in console that cannot create a directory because it already exists
server takes longer than usual to start up
plugins start timing out like this example here https://mcpaste.io/92f0167e3bd671f0

**Expected behavior**
Server to startup, all plugins are updated

**Raspberry Pi (please complete the following information):**
 - OS: HOST OS VERSION
[balenaOS 2.101.7+rev1]
SUPERVISOR VERSION
[14.0.15]

**Minecraft (please complete the following information):**
 - Device: Custom build
 - OS: Win 10
 - Minecraft Edition Java
 - Minecraft Version 1.19.2

**Comment by AlexProgrammerDE** [comment]
How is the machine connected to the internet?

**Comment by ARamlall** [comment]
both wired and it has the wifi as a backup but does not connect because of it being wired.
