### ISSUE TITLE
[BUG] Invalid or Corrupt jarfile paper.jar even with ENABLE_UPDATE set to true

### ISSUE THREAD

**Issue by JoMaZu787** [AlexProgrammerDE/balena-minecraft-server#199]
When I try to start my server from the balena dashboard, I get an error saying ` Error: Invalid or corrupt jarfile paper.jar` over and over again.

What should happen (To my knowledge) is that the server downloads the .jar file and simply starts up like any other MC server.

*Setup*
— Device: Raspberry Pi 4
— OS: balenaOS 2.105.1+rev1
— Minecraft Edition: Java Edition
— Minecraft Version: 1.19.2

**Screenshots**
![image](https://user-images.githubusercontent.com/63924520/196511024-f6dd1297-bd35-4715-98db-b8aa5277cbba.png)

**Comment by JoMaZu787** [comment]
> Hey! Have you tried replacing the paper.jar file manually via FTP already ? This is a pretty common bug on install and this usually fixes it. If you need more instructions on how to perform this, feel free to reply to this comment!

I've tried so use the scp-server service built into balena-minecraft-server, but it doesn't seem to work.

**Comment by JoMaZu787** [comment]
There is also an error saying `mkdir: cannot create directory â: File exists`

**Comment by taedium8vitae** [comment]
I'm not sure I clearly understand what you're talking about when you talk about the `scp server`.
Try using Filezilla and connect to the local IP adress of your server, navigate to the `server files` folder and replace the `paper.jar` file with the latest jar file you downloaded from their [website](https://papermc.io/downloads).
