### ISSUE TITLE
[FEATURE]MC Server Scheduled Restart

### ISSUE THREAD

**Issue by RealPoisonDart** [AlexProgrammerDE/balena-minecraft-server#20]
Hello, I absolutely love this project me and my friends have had such a good time with the server! I wanted to know if you could help with creating a scheduled restart once per day for the server. I know this can be done using a crontab event but I am not too familiar with docker or balena so I cannot figure out how to make this a reality. This could also be a really cool feature that could be added as maybe an optional service within the docker if you wanted to.

**Comment by AlexProgrammerDE** [comment]
@RealPoisonDart you dont need a crontab or something like this. This is the job of plugins. I think you are searching something like this: https://www.spigotmc.org/resources/1-8-1-15-ultimateautorestart-need-an-autorestart-plugin-grab-the-best-one-today.64414/

To install it just drag and drop it to the plugins folder via SCP.

**Comment by RealPoisonDart** [comment]
Thanks! I got an auto-restart plugin setup.
