### ISSUE TITLE
How to install Bedrock edition

### ISSUE THREAD

**Issue by andrewstech** [AlexProgrammerDE/balena-minecraft-server#21]
I see at the that bedrock is listed under the custom server of your article. I was wondering on how to install it as I believe that bedrock is not based of Java.

Thanks for any help.
Andrew

**Comment by AlexProgrammerDE** [comment]
@andrewstech i think you are right. I will look into it soon.

**Comment by andrewstech** [comment]
I have just found out that bedrock edition server wont run on ARM based platforms.

**Comment by AlexProgrammerDE** [comment]
@andrewstech i haven't tested it yet. I will try it now.

**Comment by Dizzyswirl** [comment]
Any updates on this? I'm attempting to host a remote server for friends with consoles and they cannot run java edition I believe.
I also have plenty of questions about the server config in general but that's a whole different topic.

Thanks

**Comment by AlexProgrammerDE** [comment]
@Dizzyswirl i think your friends can't join. The server should be in their Local area network. Connecting to dedicated servers isnt't allowed. You can try to use **phantom**. But it should be still in their LAN.

**Comment by AlexProgrammerDE** [comment]
@andrewstech sorry for my inactivity. I just checked it out. It isn't working. I will delete it from the list.

**Comment by andrewstech** [comment]
Never mind but thanks for having a look for me.

**Comment by CactiChameleon9** [comment]
You could try running GeyserMC alongside... I am attempting to do this
