### ISSUE TITLE
Configuring the server/Setting up remote access

### ISSUE THREAD

**Issue by Dizzyswirl** [AlexProgrammerDE/balena-minecraft-server#22]
I have followed the guide and probably a 100 other pages/guides/forums trying to find what I need but haven't quite got it but I know i'm close. 

I've setup the server and everything seems to work locally (SCP window, playing the game on a local pc running Java edition, etc.) but I can't seem to get the server set up for remote/non-local play. I have a No-IP account with a hostname that's configured to update when my netgear router is assigned a new IP from ISP (DDNS configuration), but there's something with my port forwarding settings that's probably wrong. I followed the No-IP guide best I could for port-forwarding netgear routers and this is my configuration screen:
![image](https://user-images.githubusercontent.com/64630189/80839654-4a511c00-8bc1-11ea-803c-ef88348d2dbb.png)

I set the service to 25565 port and used that service for the ip of 192.168.024 (I think i managed to set it to static?) which is what my Pi has been connecting to and matches the Balena dashboard IP.
However, either this configuration is wrong or i'm using the wrong connection method in game.
In game under direct connect i'm doing https://myhostname.ddns.net:25565 where myhostname is being replaced by my actual hostname on No-IP dashboard.

Any help would be great!

Thanks

**Comment by AlexProgrammerDE** [comment]
@Dizzyswirl uhm. You are using the wrong ip. You put in the LAN ip. This ip can be only accessed in your own network. Noip is not able to connect to this ip. What Router do you have? I will then search a way for you to get the external ip, which works with no ip

**Comment by AlexProgrammerDE** [comment]
You can also try this guide for getting the correct ip adress: https://kb.netgear.com/000060614/How-do-I-find-the-IP-address-of-a-device-connected-to-my-router

**Comment by Dizzyswirl** [comment]
I have a Netgear D6200. I thought the idea of port forwarding was to take an external request and send it to specific LAN IP and vice versa? Which IP do i need to configure it for?

**Comment by Dizzyswirl** [comment]
After playing with the settings on my router I found a work around and it's accessible through my public IP. Thanks for input, now to try and find a version that works across all platforms.
