### ISSUE TITLE
dockercraft craziness

### ISSUE THREAD

**Issue by tmigone** [AlexProgrammerDE/balena-minecraft-server#23]
Hey Alex, someone shared this we me today: https://github.com/docker/dockercraft

It's completely crazy LOL. It allows you to control and visualise docker containers from inside Minecraft 🤣 You could theoretically have the containers on a balena device (including the supervisor) show up in here using `io.balena.features.balena-socket` to map the docker/balena engine socket.

The project looks abandoned (last commit is 3 years ago), but I wanted to share it with you in case you haven't seen it because it's too awesome not to.

**Comment by AlexProgrammerDE** [comment]
@tmigone wow that seems very cool. I will check it out. But the chances are low. It is very old. Some things might be brocken.

**Comment by AlexProgrammerDE** [comment]
It looked like a good project, buuuut it doesnt work. 🙁 Yeah.. Lets hope docker will update it in the future. I would ❤️ this. Just because its soo different from anything i ever saw with docker.
