### ISSUE TITLE
Where is the option to enable DOUBLE_RAM?

### ISSUE THREAD

**Issue by nathananderson98** [AlexProgrammerDE/balena-minecraft-server#27]
Where is the option to enable my 4Gb pi to run with 2GB of ram? I had trouble finding that from the instructions in the tutorial here as well from the balena website. I have the server running and port forwarded, everything works swimmingly, just hoping to increase the loaded chunks. Thanks

**Comment by AlexProgrammerDE** [comment]
@nathananderson98 use this guide to set the variable: https://www.balena.io/docs/learn/manage/serv-vars/ I think 2G of RAM would not make a huge difference. A fast micro sd could be the better choice.

**Comment by nathananderson98** [comment]
Awesome, thanks for the feedback! The server runs great
