### ISSUE TITLE
[FEATURE] Raspberry Pi 4 8GB

### ISSUE THREAD

**Issue by filiptronicek** [AlexProgrammerDE/balena-minecraft-server#28]
**Is your feature request related to a problem? Please describe.**
A new Raspberry Pi 4 with 8GB of RAM has dropped.

**Describe the solution you'd like**
I think the README should reflect the new version (and perhaps also the code, I am not sure if anything is software-locked). Just to mention it, if it's even worth it to have 8GB of RAM for a Minecraft server (why and for whom?)

**Comment by toneymar** [comment]
> **Is your feature request related to a problem? Please describe.**
> A new Raspberry Pi 4 with 8GB of RAM has dropped.
> 
> **Describe the solution you'd like**
> I think the README should reflect the new version (and perhaps also the code, I am not sure if anything is software-locked). Just to mention it, if it's even worth it to have 8GB of RAM for a Minecraft server (why and for whom?)

I agree, I just got the 8GB version for myself. Might be overkill, but maybe there is a way an option could be added for allocating 4GB of ram to the server? My Minecraft server is running like a dream, thanks for all your work Alex!!

**Comment by Skidushe** [comment]
You should be able to edit the start.sh script and make a pull request!

**Comment by filiptronicek** [comment]
Sadly I cannot test it myself :(

**Comment by Skidushe** [comment]
Testing shouldn't be an issue, try make an environment variable reflecting the amount of RAM used and set that as the Xms and Xmx properties at the bottom of /minecraft-server/start.sh

**Comment by AlexProgrammerDE** [comment]
Sorry for my inactivity. I will work now on it.

**Comment by AlexProgrammerDE** [comment]
Ok now can the users directly set the RAM allowance. I will test it soon and merge. Btw: I will add a balena deploy button to the README which automaticly pushes the code to your fleet. It might take some days or weeks till the blog posts get updated. I have no direct access to that since i dont work at balena.

**Comment by filiptronicek** [comment]
Awesome, thanks for resolving the issue!

**Comment by AlexProgrammerDE** [comment]
The deploy feature didnt work i opened a issue in balena sound for this.
