### ISSUE TITLE
RAM Variable

### ISSUE THREAD

**Issue by Dizzyswirl** [AlexProgrammerDE/balena-minecraft-server#30]
Hello, I have a rpi4 with 4gb of ram and I noticed you updated the DOUBLE_RAM variable to just RAM to allow allocation beyond 2gb which is great, however my pi is just using the default now. I installed a different (newer) version of balenaOS, i think 1.51, as i was wanting my minecraft server on a different SD card, however when I set the Device Variable "RAM" to "4G" it's only using 1gb.

Any help would be great, it's probably something simple.

**Comment by AlexProgrammerDE** [comment]
@Dizzyswirl setting the variable is first of all a bad idea. The OS and other containers need Ram too. What message do you get? Can you give me a screenshot?

**Comment by Dizzyswirl** [comment]
The screenshots of the log and variables are attached. I changed the variable to 2gb as I forgot the OS would also need ram to run the server, but it's still bootting with 1gb towards the top of the log screenshot.
![PiMC Variables](https://user-images.githubusercontent.com/64630189/84841613-722cff80-b008-11ea-8c66-380486f4710c.png)

![PiMC Log](https://user-images.githubusercontent.com/64630189/84841604-6ccfb500-b008-11ea-8b3a-15c47ce5b224.png)

**Comment by AlexProgrammerDE** [comment]
@Dizzyswirl ok the only reason for this which i can think of is that you didnt update to the latest version of balena-minecraft-server.

**Comment by Dizzyswirl** [comment]
That’s probably it, do I just download the newer repo and then push to balena?

**Comment by AlexProgrammerDE** [comment]
@Dizzyswirl yes

**Comment by Dizzyswirl** [comment]
I pushed it, it all updated and server started with correct ram, thank you! I knew it would be something simple.
