### ISSUE TITLE
Updating to 1.16

### ISSUE THREAD

**Issue by chazzytho** [AlexProgrammerDE/balena-minecraft-server#31]
I tried looking around on the internet but couldn't really find anything, so I hope it's ok if I ask here.

I was wondering how you would recommend updating the balena minecraft server to 1.16 and resetting the nether once the spigot and paper versions are released. 
Here's what I was thinking:

1. stop the minecraft server
2. connect to the Pi4 using SCP
3. backup the world files
4. update to 1.16
5. delete level.dat file from nether folder
6. restart the server

I would greatly appreciate any help I can get with step 4 or any corrections you would have for the rest of the process. Thanks in advance!

**Comment by AlexProgrammerDE** [comment]
@chazzytho Hi! I will update the URL when  the 1.16 paper is released. You can then push the new version and then set `ENABLE_UPDATE` to `true`. The server will then get the newest version and starts it. You dont have to delete any level.dat files. Theres a automatic upgrading mechanism i think.

**Comment by AlexProgrammerDE** [comment]
But if you want a completely new nether just delete the whole folder.

**Comment by chazzytho** [comment]
Great, thanks for the help! Really looking forward to this update

**Comment by Bracciata** [comment]
Just wanted to note the first version is out and if there is any way I can help with this I am a developer who really likes this project!

**Comment by AlexProgrammerDE** [comment]
@Bracciata I just saw it too. Its time to update.

**Comment by Bracciata** [comment]
@AlexProgrammerDE  Do you have a guide for pushing the new version?

**Comment by AlexProgrammerDE** [comment]
@Bracciata yes. Just follow the sgeps above to upgrade the version.

**Comment by Bracciata** [comment]
@AlexProgrammerDE Is there an easy to use way to push up the repo a second time? Or is using git pull an option?

**Comment by AlexProgrammerDE** [comment]
@Bracciata yes. Just download the code a secound time and push it again to balena via the clie.

**Comment by Bracciata** [comment]
After pushing the repo I am getting the following issue 
```
28.06.20 08:18:56 (-0600)  mc-server  Error reading patch file
28.06.20 08:18:56 (-0600)  mc-server  java.io.EOFException: Unexpected end of ZLIB input stream
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:466)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:159)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.io.FilterInputStream.read(FilterInputStream.java:133)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.io.BufferedReader.read1(BufferedReader.java:210)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.io.BufferedReader.read(BufferedReader.java:287)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.io.Reader.read(Reader.java:229)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.util.Properties$LineReader.readLine(Properties.java:500)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.util.Properties.load0(Properties.java:415)
28.06.20 08:18:56 (-0600)  mc-server    at java.base/java.util.Properties.load(Properties.java:378)
28.06.20 08:18:56 (-0600)  mc-server    at io.papermc.paperclip.PatchData.parse(PatchData.java:55)
28.06.20 08:18:56 (-0600)  mc-server    at io.papermc.paperclip.Paperclip.setupEnv(Paperclip.java:79)
28.06.20 08:18:56 (-0600)  mc-server    at io.papermc.paperclip.Paperclip.main(Paperclip.java:45)
```
![image](https://user-images.githubusercontent.com/13560664/85950129-36ebd400-b918-11ea-9297-4ad0dfcbb685.png)

**Comment by AlexProgrammerDE** [comment]
@Bracciata maybe its a paper side issue.

**Comment by jazzyminecraft** [comment]
Quick questions.

1) What is sgeps ?

2) Has the paper side issue been fix?

3) Should we do a clean install or upgrade?

New to this so please excuse any dumb questions as both my kids and I are learning.

P.S. Thanks for making this project. I am using this to teach my kids some system management and how command line works. Would have been difficult to get them interested in this without a project like this.

**Comment by AlexProgrammerDE** [comment]
@jazzyminecraft hi! 
1. I dont know what that is. Where did you read this.
2. I didnt check it yet. I will try it later.
3. Yes. Maybe that helps.

You had this issue too?

**Comment by jazzyminecraft** [comment]
I think you replied above:
@Bracciata yes. Just follow the sgeps above to upgrade the version.

> @jazzyminecraft hi!
> 
> 1. I dont know what that is. Where did you read this?
> 2. I didnt check it yet. I will try it later.
> 3. Yes. Maybe that helps.
> 
> You had this issue too?

**Comment by jazzyminecraft** [comment]
Sorry, I figured it out. Type I think you meant steps above. I thought it was an acronym.
