### ISSUE TITLE
Unable to determine local host IP

### ISSUE THREAD

**Issue by Kuiper03** [AlexProgrammerDE/balena-minecraft-server#32]
The world generating process start and finish, but i cant access on minecraft.

1. Restart or Turn on raspberry
2. Scroll down to on logs, after world generation
3. See error.

In logs it says "Unable to determine local host IP, please set server-ip in server.properties: balenaminecraftserver: balenaminecraftserver: No address associated with hostname". 
I tried to put the id of the raspberry and the public ip of my router. It didn't work

![immagine](https://user-images.githubusercontent.com/67398122/85639649-a8622300-b689-11ea-871a-c63214a2de03.png)
![immagine](https://user-images.githubusercontent.com/67398122/85774982-a480e000-b71f-11ea-8d6b-409a5436d91a.png)

Raspberry Pi:
 - OS: [balenaOS 2.51.1+rev1]
 - Version [11.4.10]

Minecraft:
 - Device: [PC]
 - OS: [Win10]
 - Minecraft Edition [Java Edition]
 - Minecraft Version [Optifine 1.15.2 shinigima]

I priviously had a paper.jar error, but i resolved it like in other threads

**Comment by Kuiper03** [comment]
Ok, forget it, I discovered that actually i took the wrong ip, but i still have a problem :-/.

![immagine](https://user-images.githubusercontent.com/67398122/85774982-a480e000-b71f-11ea-8d6b-409a5436d91a.png)

**Comment by Kuiper03** [comment]
Ok, I'm sorry.
I found out the problem: i had to set server.properties->online=false

My bad!!

**Comment by nafeisweixelman** [comment]
How can you set the server.properties -> online=false?
I am running into the same issue.

**Comment by eddy991** [comment]
hi, i have the same problem " [19:28:32 WARN]: Unable to determine local host IP, please set server-ip in server.properties"
how can i set server.properties?

**Comment by Kuiper03** [comment]
Yeah, found, that's it.
Thanks!
