### ISSUE TITLE
Can't connect to the minecraft server via WinScp outside of the LAN

### ISSUE THREAD

**Issue by MadMowgli** [AlexProgrammerDE/balena-minecraft-server#34]
**Connection timed out**
So we've set up a balena minecraft server on a Raspberry Pi 4 (8Gb RAM), went for the dev-OS installation, connected smoothly to both the gameserver as well as the scp-server, took the Pi to it's new location where it's meant to stay and connected to both servers again without any problems. Through out all those connections we always were in the same local network as the Pi itself.

Now when we try to connect to the scp-server from home, without being in the same LAN as the Pi, WinScp is searching for the host and gives us a **Connection timed out** error as shown below. 

![SearchingForHost](https://user-images.githubusercontent.com/45829573/86099630-0b9feb00-bab8-11ea-9780-277a1db2d30b.png)
![ConnectionTimedOut](https://user-images.githubusercontent.com/45829573/86099639-0e024500-bab8-11ea-81fe-afd6f219a143.png)

The IP-adress is blended out, since we're trying to connect over the external server IP. As soon as we WinScp-connect over the local network, sitting right next to the Pi and using the internal IP, we can connect without problem. So, what are we doing wrong?

**What we've tried**
* Followed WinScp's [guide](https://winscp.net/eng/docs/message_connection_refused) on the error
** Extended the server response timeout
** Introduced WinScp to the firewall
* Checked if all the ports were open on the Pi - all required Ports (in this case Port 22) are open
* Tried FileZilla - gets the error as well

**Raspberry Pi (please complete the following information):**
 - OS: balenaOS 2.51.1+rev1 (development)
 - SuperVisor version: 11.4.10

**Minecraft (please complete the following information):**
 - Device: Raspberry Pi4 (8Gb RAM)
 - OS: balenaOS 2.51.1+rev1 (development)
 - Minecraft Edition Java Edition
 - Minecraft Version 1.15.2

**Comment by AlexProgrammerDE** [comment]
@MadMowgli so do i understand that right? You cant connect to the Pi outside of  the network the Pi is in? You will need to port forward the port 22 on the Pi and use the public ip to connect to it through the web.

**Comment by MadMowgli** [comment]
Yes, that's right. I can't connect to the Pi outside of the network the Pi is in!
Okay, so I need to set up port forwarding on the Pi itself? So basically I forward all incoming traffic from port 22 to port 22? Do you know the linux commands for it?

**Comment by AlexProgrammerDE** [comment]
@MadMowgli no. The Pi is good. You will need to allow the port in the router. And use the public ip of the Pi.

**Comment by MadMowgli** [comment]
Will give it a try. Should I forward all the ports minecraft uses? Like: 25565, 25575, 22

**Comment by AlexProgrammerDE** [comment]
@MadMowgli no port 22 is all you need for SCP. But if you want to play from somewhere else than forward the other ports too.

**Comment by MadMowgli** [comment]
Worked just fine. Forwarded all the ports, now i'm able to connect to all the services.
Huge support, 10/10 would recommend.
