### ISSUE TITLE
DOUBLE_RAM does not work with newer paper.jar file. [BUG]

### ISSUE THREAD

**Issue by SethHering** [AlexProgrammerDE/balena-minecraft-server#35]
DOUBLE_RAM does not work when using a 1.16.1 paper-91 jar file.

**To Reproduce**
Go to https://papermc.io/downloads
Download the newest version of paper
Replace the paper.jar file with the new on using SCP
Set DOUBLE_RAM to true

**Expected behavior**
I expected the DOUBLE_RAM variable to allow the jar file to use 2 GB of RAM. However it did not. It still starts with 1 GB of RAM. While I was using the original 

**Raspberry Pi (please complete the following information):**
 - OS: [balenaOS 2.47.1+rev1
 - Superior Version 10.6.27

**Minecraft (please complete the following information):**
 - Minecraft Edition Java Edition
 - Minecraft Version 1.16.1

**Comment by AlexProgrammerDE** [comment]
@SethHering we renamed it. Please use `RAM` and set it to `2G`

**Comment by SethHering** [comment]
> @SethHering we renamed it. Please use `RAM` and set it to `2G`

@AlexProgrammerDE Hi, when I set it to 3G or 4G the server does not act like it is even running on more than one GB of RAM. It crashes even with only one person on. Is it able to run on 3 GB or 4 GB of RAM or does it only work with 1GB? The weird thing is it even let me set the RAM variable to 12 and the output said it started the server at 12G of RAM which is impossible because my pi only has 4 GB.
