### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by jtorres-dev** [AlexProgrammerDE/balena-minecraft-server#36]
**Describe the bug**
There is an error when attempting to start the mc-server service. mc-server logs show:
`
mc-server  Starting jar file with: 1G of RAM
20.07.20 16:33:34 (-0500)  mc-server  Error: Invalid or corrupt jarfile paper.jar
20.07.20 16:38:46 (-0500)  mc-server  Setting device hostname to: balenaminecraftserver
20.07.20 16:38:46 (-0500)  mc-server  OKStarting jar file with: 1G of RAM
20.07.20 16:38:46 (-0500)  mc-server  Error: Invalid or corrupt jarfile paper.jar
`
and continues an infinite loop.

**To Reproduce**
Steps to reproduce:
1. Follow the tutorial. Once on balena dashboard with Pi running all services after running balena push <appName>, the mc-server gives issues on attempting to start with paper.jar

**Expected behavior**
I believe the mc-server service automatically fetches  the download for paper.jar from a website, however it seems to fail for mine. 

**Raspberry Pi (please complete the following information):**
 - OS: [balenaOS 2.51.1+rev1]
 - Version 11.4.10

**Additional context**
I've attempting to download the paper.jar file directly to the mc-server folder, then using `balena push <appName>` but it detects it as too large of a file and ignores it from the push.

![firefox_aoaADOkXgp](https://user-images.githubusercontent.com/55565569/87990003-bba9b800-caa8-11ea-9830-a5e8f6676cd2.png)

**Comment by SethHering** [comment]
I had this same issue. In order to fix log into SCP and delete the current paper.jar file. Then go into balena cloud and restart the device. This should fix the issue.
