### ISSUE TITLE
[BUG] Not able to upgrade from 1.16.1 to 1.16.3

### ISSUE THREAD

**Issue by pwestbro** [AlexProgrammerDE/balena-minecraft-server#42]
The upgrade code will have a problem if paper.java file for a newer version of the minecraft server is smaller than the previous version.

Currently, the the "-c" parameter is passed to the wget command.  This will only download new bytes if the new file is a lager size than the previous version.  Also this will only download the delta in bytes, which may not be right, if changes to the jar happened anywhere besides the tail of the file.

https://github.com/AlexProgrammerDE/balena-minecraft-server/blob/cb7d60b815859e5c815704f8ca1a1307ce8fd34b/mc-server/start.sh#L39

I noticed this when trying to upgrade from 1.16.1 to 1.16.3, as the 

1.16.1 jar is 46982714 bytes, while the 1.16.3 jar is 46848610 bytes.

**Comment by christian4423** [comment]
Would you suggest taking the -c out?

**Comment by pwestbro** [comment]
Unfortunately that doesn't really fix the problem, as without the -c option, the file is download every time the script is run.

I wonder if it would be better to use curl with the -z flag

https://superuser.com/questions/908293/download-file-via-http-only-if-changed-since-last-update

**Comment by christian4423** [comment]
That seems like a solid option. 
Probably a silly question here but if I run balena push <AppName> with these changes, will my save files be okay? 
If they will, I can try it out. 

I am having this issue going from 1.16.3-->1.16.4

**Comment by pwestbro** [comment]
This worked for me.  (I did this when I was testing removing the -c flag)

One thing that I am not sure of is whether the file that was downloaded by wget will be considered valid for curl when the -z flag is used

**Comment by christian4423** [comment]
Did you switch it to `curl -o "paper.jar" -z "paper.jar" "https://papermc.io/ci/job/Paper-1.16/lastSuccessfulBuild/artifact/paperclip.jar" && break`

@AlexProgrammerDE may you verify that?

**Comment by pwestbro** [comment]
I haven't had a chance to try the switch to the curl call.  From the docs, it seems that the -z flag would need to be optionally added.  It seems that it won't work on the first download of the jar file.

**Comment by christian4423** [comment]
I was reading that. A commentor stated that if you are one a recent update that the -z flag wont error on first download
