### ISSUE TITLE
How to create a server with forge

### ISSUE THREAD

**Issue by EvilNick2** [AlexProgrammerDE/balena-minecraft-server#44]
I was looking through the documentation for the server and I couldn't seem to find anything about how to change the server from vanilla/paper to forge/modded and was wondering how that would be done?

**Comment by hibikutek** [comment]
I've done it recently, and the gist of it is to put the minecraft forge server jar into the `mc-server/serverfiles` folder.  This folder would also contain anything else that should be in the server folder, so put your mods and config files there.  If you are running a server locally, you can literally copy that entire folder to the `mc-server/serverfiles` folder.  Then you are going to need to create an environment variable called `JAR_FILE` and set it to the forge file.

For an example of the variables that I have, see here:
![image](https://user-images.githubusercontent.com/2807240/96103112-2feccf80-0ecf-11eb-8791-332e001491db.png)

**Comment by hibikutek** [comment]
Ignore the waits at the bottom, I edited the script to change the frequency of wifi connect and mc-server attempting to start.

**Comment by AlexProgrammerDE** [comment]
@hibikutek yeah thanks for the help here. :heart: I just wanted to start to reply all issues. I am gonna close this now.  @EvilNick2 hibikuteks answer is completely correct.
