### ISSUE TITLE
Does this server connect to Minecraft PE?

### ISSUE THREAD

**Issue by j-dogcoder** [AlexProgrammerDE/balena-minecraft-server#45]
Hi there, Does this project create a Minecraft server accessible by Minecraft PE players?

**Comment by AlexProgrammerDE** [comment]
@j-dogcoder yes and no... So the server noes not support this natively. I tried earlier to run a normal bedrock server on it, but the result is that the architecture isn't the right one to use for it. There is also a project called [Pocketmine-MP](https://github.com/pmmp/PocketMine-MP) it requires php installed what we don't have and also a different startup command. And im also not sure if it will work. The solution i recommend is using [GeyserMC](https://github.com/GeyserMC/Geyser its a plugin that allows you to join with minecraft pe ona java server, but some stuff is still missing and needs no be added to the project, but its the best solution for now. When adding it don't forget to forward the default pe port.

**Comment by j-dogcoder** [comment]
Ok. Thanks!
