### ISSUE TITLE
Could you Please write how to update the server on the tutorial

### ISSUE THREAD

**Issue by PickleWarrior151** [AlexProgrammerDE/balena-minecraft-server#46]
Hi am having trouble updating my server from 1.16.1 to 1.16.3. Could you add this to the tutorial.

**Comment by AlexProgrammerDE** [comment]
Hi its just setting `ENABLE_UPDATE` to `true`. Your right the docs need a lot of rework, but I don't really find much time for it lately, but its on my todo.

**Comment by PickleWarrior151** [comment]
Ok thank you, is that on balena dashboard or WinSCP server files?

**Comment by AlexProgrammerDE** [comment]
@PickleWarrior151 its a balena dashboard variable.

**Comment by PickleWarrior151** [comment]
> @PickleWarrior151 its a balena dashboard variable.

![image](https://user-images.githubusercontent.com/69131536/96508297-63f62680-1228-11eb-8e9e-a8c9a2c6ca85.png)
Like this?

**Comment by AlexProgrammerDE** [comment]
I think it should be lowercase, but yes.

**Comment by PickleWarrior151** [comment]
> I think it should be lowercase, but yes.

Alright Thanks
