### ISSUE TITLE
1GB of ram

### ISSUE THREAD

**Issue by PickleWarrior151** [AlexProgrammerDE/balena-minecraft-server#47]
Hi so it says my server has a max of only 1GB and I am running on a raspberry pi 4 with 4GBs of ram. If you could help me fix this that would be great.

**Comment by AlexProgrammerDE** [comment]
I don't see a issue here. You can set more ram through the RAM variable.

**Comment by PickleWarrior151** [comment]
> I don't see a issue here. You can set more ram through the RAM variable.

Ok what should I set the name and value to and I'm guessing the service is mc-server?

**Comment by AlexProgrammerDE** [comment]
> > I don't see a issue here. You can set more ram through the RAM variable.
> 
> Ok what should I set the name and value to and I'm guessing the service is mc-server?

RAM, as an example 2G and yes

**Comment by PickleWarrior151** [comment]
> > > I don't see a issue here. You can set more ram through the RAM variable.
> > 
> > 
> > Ok what should I set the name and value to and I'm guessing the service is mc-server?
> 
> RAM, as an example 2G and yes

So would it be service: mc-server Name: 2g value: yes

**Comment by EvilNick2** [comment]
@PickleWarrior151 It would be like this
![image](https://user-images.githubusercontent.com/72648332/97642107-4bfa8000-1a3c-11eb-9f86-7afa5f6accea.png)

**Comment by PickleWarrior151** [comment]
Ok I'm running my server on paper on Minecraft version 1.16.3 and paper version 247. Is this how you would so it for paper?
![image](https://user-images.githubusercontent.com/69131536/97651208-d093d100-1a31-11eb-94b4-7163a0b31a25.png)

**Comment by EvilNick2** [comment]
It should have to be all capitals so it would be
RAM 6G instead of ram 6g

**Comment by PickleWarrior151** [comment]
> It should have to be all capitals so it would be
> RAM 6G instead of ram 6g
Ok so it starts with 2GBs of RAM but then I get this error with the Jar_file variable
Error: Unable to access jarfile paper-1.16.3-247

**Comment by EvilNick2** [comment]
No you shouldn't need that, the default jar file that the server will run is paper.jar so all you need to do is rename the file you downloaded from paper-1.16.3-247.jar to paper.jar and it should work

**Comment by PickleWarrior151** [comment]
> No you shouldn't need that, the default jar file that the server will run is paper.jar so all you need to do is rename the file you downloaded from paper-1.16.3-247.jar to paper.jar and it should work. All though if you do ever want to use forge or something other than paper to run your server you would need to have to have it as "JAR_FILE" and the variable always has to have .jar at the end so to fix what you current have in your dashboard it would be JAR_FILE paper-1.16.3-247.jar

OK thanks

**Comment by christian4423** [comment]
Why is this reopened? You cannot set the variable to 4G or higher because your PI needs RAM for system processes. If your PI has a max of 4GB you can realistically only use 2G. 3G might be pushing it. If you want to override the environment variable and its default. Edit `./mc-server/start.sh` and change `line 12` to `"2G"` in all caps
![image](https://user-images.githubusercontent.com/6324867/98015674-0c7cbc80-1dcb-11eb-9050-4620a68d4d59.png)
