### ISSUE TITLE
WIFI Connect Error 

### ISSUE THREAD

**Issue by PickleWarrior151** [AlexProgrammerDE/balena-minecraft-server#48]
So I have been have been constantly getting this error. I have my pi hardwired with and ethernet to my router so i don't use wifi with in and I don't plan on moving it around. Its not that big of a problem its just really annoying.

27.10.20 10:59:24 (-0400)  wifi-connect  Spider mode enabled. Check if remote file exists.
27.10.20 10:59:24 (-0400)  wifi-connect  --2020-10-27 14:59:24--  http://www.google.com/
27.10.20 10:59:24 (-0400)  wifi-connect  Resolving www.google.com (www.google.com)... 172.217.12.164, 2607:f8b0:4006:814::2004
27.10.20 10:59:24 (-0400)  wifi-connect  Connecting to www.google.com (www.google.com)|172.217.12.164|:80... connected.
27.10.20 10:59:24 (-0400)  wifi-connect  HTTP request sent, awaiting response... 200 OK
27.10.20 10:59:24 (-0400)  wifi-connect  Length: unspecified [text/html]
27.10.20 10:59:24 (-0400)  wifi-connect  Remote file exists and could contain further links,
27.10.20 10:59:24 (-0400)  wifi-connect  but recursion is disabled -- not retrieving.
27.10.20 10:59:24 (-0400)  wifi-connect  
27.10.20 10:59:24 (-0400)  wifi-connect  Skipping WiFi Connect

**Comment by AlexProgrammerDE** [comment]
@PickleWarrior151 its not a error. Its log. We include wifo connect in the project. It opens a WiFi network if it doesn't find a known wifi network. You can then connect to it and your friends too and play directly over the pus wifi.

**Comment by AlexProgrammerDE** [comment]
If you don't like it just remove the container from the docker compose file and remove the folder itself.

**Comment by PickleWarrior151** [comment]
> @PickleWarrior151 its not a error. Its log. We include wifo connect in the project. It opens a WiFi network if it doesn't find a known wifi network. You can then connect to it and your friends too and play directly over the pus wifi.

Ok, thanks for clarifying.
