### ISSUE TITLE
[QUESTION] How to attach a debugger to the minecraft server?

### ISSUE THREAD

**Issue by MadMowgli** [AlexProgrammerDE/balena-minecraft-server#50]
Simple question: [This guide on BukkitWiki](https://bukkit.gamepedia.com/Plugin_debugging) explains how you can attach an IDE's debugger to the minecraft server by editing the startup command line arguments. Where do I configure those startup arguments for my balena mc-server?

**Comment by EvilNick2** [comment]
@MadMowgli I'm pretty sure the file that you need to edit is in the github repo in mc-server 
![image](https://user-images.githubusercontent.com/72648332/97640911-ae9e4c80-1a39-11eb-9482-effcbc9c6000.png)
Then edit start.sh with whatever editing program you use (e.g notepad++)
![image](https://user-images.githubusercontent.com/72648332/97641001-d8577380-1a39-11eb-8920-78820834e494.png)
![image](https://user-images.githubusercontent.com/72648332/97641119-18b6f180-1a3a-11eb-8577-df172f0b6932.png)
The part I've highlighted in the above picture is the command that will initialise the server on every launch but I'm pretty sure the thing you would need to edit will be somewhere in that start.sh file

**Comment by AlexProgrammerDE** [comment]
Thats exactly how to do it. Thanks @EvilNick2 ! I don't see any reason btw to even add a debugger. Server developement should happen on the ide host itself in my opinion.
