### ISSUE TITLE
[QUESTION] Pi stats and console on display

### ISSUE THREAD

**Issue by Liliacchan** [AlexProgrammerDE/balena-minecraft-server#52]
Would it be possible in any way to connect a display to a Pi and have it show the Pi statistics and mc console.
If this is possible how and what can you display on it.

**Comment by AlexProgrammerDE** [comment]
@Liliacchan i agree this would be a nice feature to add, but the pi has no built in desktop enviroment. That means we can't show any images.

**Comment by Liliacchan** [comment]
So the pi showing the balena image is just something you cant change i would feel from this?\

**Comment by chrisys** [comment]
If there's some kind of terminal/console program we could use to show stats that would be pretty easy to get running. Any kind of web frontend interface to the server would be easy too, as we can use the [browser block](https://github.com/balenablocks/browser) to show it on a display.

**Comment by AlexProgrammerDE** [comment]
@chrisys i think there was some server plugin called "Plan". It is able to show many stats about the server on a Webserver itself runs.

**Comment by Liliacchan** [comment]
How would i beable to add this browser block to my existing device?

**Comment by AlexProgrammerDE** [comment]
> beable

You just add the block and directory into your docker-compose file and see how it goes.

**Comment by AlexProgrammerDE** [comment]
I will close this for now. For everyone looking for a solution to this: Use the plan plugin to get server insights into the browser. You could probably also display those on a pi touchscreen through the balena webbrowser block.
