### ISSUE TITLE
Question, how do you input command and set up server ranks?

### ISSUE THREAD

**Issue by Dante-Morrison** [AlexProgrammerDE/balena-minecraft-server#53]
i have everything set up and operational, but im not sure how to modify the ranks. putting commands directly into the mcserver terminal on balena brings up filepath errors and the ops.json file is blank so i dont even know how to really start.

**Comment by EvilNick2** [comment]
You can't put commands in on that console, you need to download a program to connect to RCON. If you read the tutorial on the main page it mentions something about RCON

**Comment by AlexProgrammerDE** [comment]
I added a rcon container recently. If you try to open terminal in it you should be able to manage your server.

**Comment by EvilNick2** [comment]
I tried to use that but it just returned an error when trying to use commands

**Comment by AlexProgrammerDE** [comment]
Weird. May you show me the error in a new issue @EvilNick2 ? I will close this issue for now.
