### ISSUE TITLE
[BUG] Cannot upgrade from 1.16.3 to 1.16.4

### ISSUE THREAD

**Issue by christian4423** [AlexProgrammerDE/balena-minecraft-server#54]
**Describe the bug**
I am unable to get the update file for version 1.16.4.

**To Reproduce**
1. I have ENABLE_UPDATE=true
2. In HostOS I do the following commands: 
3. find . -name "*paper.jar" -exec rm -rf {} \;
4. find . -name "\*1.16.3\*" -exec rm -rf {} \;
5. find . -name "*copied.txt" -exec rm -rf {} \;
6. Restart mc-server
7. I see `Starting minecraft server version 1.16.3` in the logs

**Expected behavior**
Since `https://papermc.io/ci/job/Paper-1.16/lastSuccessfulBuild/artifact/` shows the correct version, I do not know why it is not using 1.16.4.

**Screenshots**

**Raspberry Pi 8GB:**

**Comment by christian4423** [comment]
👍

**Comment by AlexProgrammerDE** [comment]
@christian4423 
1. Its ENABLE_UPDATE
2. github has reactions as i did above. No need to comment a thumb up...

**Comment by AlexProgrammerDE** [comment]
Oh it was different in the email

**Comment by christian4423** [comment]
Hi Alex, I had a typo in my post but had it right on the server. I am guessing my issues is because https://getbukkit.org/download/vanilla has not realeased 1.16.4

**Comment by Drewq2004** [comment]
I have the same issue where ENABLE_UPDATE=true but minecraft client running 1.16.4 can't connect to server because its running 1.16.3

**Comment by AlexProgrammerDE** [comment]
Do you guys get when running with the variable enabled a download log?

**Comment by AlexProgrammerDE** [comment]
Also if you really want to update soon. You can try to download it manually from https://papermc.io/ and move it over and replace the old jar file?

**Comment by Drewq2004** [comment]
Thank you.  FTP into pi and dropped in new jar and worked. Thank you.  If I place a forge jar in will that work too?  Would I need a .YML file too.  Assuming the YML is the up date component?

Andrew Carl


Mobile

________________________________

**Comment by Drewq2004** [comment]
Can you tell my how to expand you java command and where it is located so I can change it for my Pi-4 8gb ram?  I wish to make sure I am using the appropriate amount of ram.  Also do you run an auto garbage can or cache clearing script to keep the Minecraft from following behind and calls?
