### ISSUE TITLE
[QUESTION] Performance 

### ISSUE THREAD

**Issue by mariusrueve** [AlexProgrammerDE/balena-minecraft-server#59]
Hello, this seems very appealing to me!

Currently I run `Raspberry Pi OS Lite` with `PaperMC 1.15.2`.
Can you say if there will be any performance improvements by switching to `balena-minecraft-server`?

I guess I will test it anyways, but it would be nice to know what I can expect.

**Comment by AlexProgrammerDE** [comment]
@mariusrueve balena minecraft server runs on balenaos. Its a lightweight production ready os. I am not sure if its as fast as the os lite, but there are other reasons than performance. A scp server is included that allows very easily to edit files from even your main pc. Also you can easily attach to the console and execute command through rcon. Its just an easy alternative to setting it all up by hand.

**Comment by mariusrueve** [comment]
@AlexProgrammerDE I will just test the performance. If it is anywhere near the lite os, the convenience of this project simply outweighs. Thanks for the answer! Really nice project 👍🏼
