### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by Pentagrade** [AlexProgrammerDE/balena-minecraft-server#6]
Hi Alex,

Just thought I'd try and raise this here as a topic. I noticed your gif showing the chunk loading and unfortunately cannot yield the same result despite using 2GB on my RPi 4 (4GB).

Do you have any advice or tips on optimizing the pi to ensure it can get the same performance yours has? Currently my console is littered with things like:
`Can't keep up! Is the server overloaded? Running 73827ms or 1476 ticks behind`

**Comment by AlexProgrammerDE** [comment]
@Pentagrade you are right with this error, but even on my gaming rig is the server sometimes overloaded. The problem is that the server is not using all of your RAM and CPU cores. Just a part of it. You maybe had tried to fly into not generated chunks (https://minecraft.gamepedia.com/Chunk)
In my gif i flied into already generated chunks. That is faster. But i think if you don't fly very fast around the world, can't this issue occur. You can also try to set a lower render distance.

**Comment by Pentagrade** [comment]
I’m guessing its not possible to push up the cpu and ram allocation a little further?

That’s fair I guess, performance is a little better when taking rendered chunks into account.

Other behaviours that occurred also when I tried to stay in the same chunk were the occasional block lag and slow mob AI too. Sometimes it got too much for it and took 10 seconds to catch up also.

**Comment by AlexProgrammerDE** [comment]
@Pentagrade i just saw how big your lags are. I had only one with 500ms. Can you say me what happens if you connect to `mc.hypixel.net`? Are you experiencing lags?

**Comment by Pentagrade** [comment]
@AlexProgrammerDE I'm not encountering the lag on servers. I launched a server on my own computer also and can see it is running smoothly with mods while playing.

**Comment by Pentagrade** [comment]
I have decided to invest in a fan for the Pi unit as I had a sneaking feeling the processor was throttling due to the temperature. The room it sits in is relatively hot and even while idle was reaching 80-90°C after longer periods of time. 

Now with the fan installed I may be correct as performance is noticeably better and little to no tick errors.

**Comment by AlexProgrammerDE** [comment]
@Pentagrade thats great news. My Pi has also a fan. I forgot to try it without one. Seems like a temperature issue. By the way you are using forge? Thats cool, but it uses lots of resources. I think i will recommend in the README a fan.

**Comment by Pentagrade** [comment]
I'd definitely recommend adding fan info to the README, it's made quite the difference to the performance overall. I'm stilling using the default Paper jar, but I do plan on finding where the limits are over time, I'll keep this issue posted with my findings.

**Comment by AlexProgrammerDE** [comment]
@Pentagrade do you have any more questions or shall i close the issue?

**Comment by Pentagrade** [comment]
I'm all good here, If notice anything else I'll reopen
