### ISSUE TITLE
Unable to connect to server files

### ISSUE THREAD

**Issue by PickleWarrior151** [AlexProgrammerDE/balena-minecraft-server#66]
So my server files had been working fine with win scp. But I haven't been using my sever for a while so I turn my pi off and unplugged it. I have recently come back to it but I can't seem to connect to my server files. My friends where able to connect to the server and play on it. I have tried restarting and rebooting I hasn't seemed to help but now I am getting this error. 
![image](https://user-images.githubusercontent.com/69131536/103036923-ce815680-4538-11eb-89b4-b885ed4ed466.png)

Raspberry Pi
 - OS: balenaOS 2.51.1+rev1
 - Version: 11.4.10

Minecraft:
 - Device: Windows 10 PC
 - OS: Windows 10 home
 - Minecraft Edition Java edition
 - Minecraft Version 1.16.4

**Comment by AlexProgrammerDE** [comment]
@PickleWarrior151 this looks weird. I think it may be related to recent changes on the dashboard. I recommend you to ask help for this error message at the top of the dashboard, in the balena forums: https://forums.balena.io/
Feel free to reopen this issue if you find out it is still related to this project. 👍🏻
