### ISSUE TITLE
[BUG]cant connect to scp server

### ISSUE THREAD

**Issue by JustToasty** [AlexProgrammerDE/balena-minecraft-server#69]
cant find the password to connect to the server

**Raspberry Pi 4 2gb**
 - OS: balenaOS 2.41.0+rev4
 - Version 22

**Minecraft**
 - OS: Windows 10 Home
 - Minecraft Edition Java Edition
 - Minecraft Version 1.16.4

**Comment by AlexProgrammerDE** [comment]
@JustToasty do you mean connecting from minecraft, scp or rcon?

**Comment by JustToasty** [comment]
im trying to connect to the scp file server through winscp but it asks me for a password, i don't know the password.

**Comment by AlexProgrammerDE** [comment]
![Screenshot_20201229-161355_GitHub.jpg](https://user-images.githubusercontent.com/40795980/103293817-e2253500-49f0-11eb-9387-d159673014b7.jpg)

Please read the documentation first...
@JustToasty

**Comment by JustToasty** [comment]
thanks, i didnt know where to look for something like that.
