### ISSUE TITLE
Player Management and Security

### ISSUE THREAD

**Issue by ManolorinCode** [AlexProgrammerDE/balena-minecraft-server#70]
Hello!

Excellent work by the way. After a few hours of working on this, I am enjoying a great server with my kids.
So thanks for that!
Question 1: Is there a way to manage/ban players after setting up remote access? And is there a way to monitor who joins?
Question 2: Are there any security steps to take when port forwarding?

Many thanks!
Manos

**Comment by DatLima25** [comment]
You can use the command in RCon `op [Username]` to add that person as an "operator". This person can now execute commands, including `/ban [Username]`.

You can also execute the command `ban [Username]` from RCon. The command is reversed by using `pardon [Username]` in RCon or `/pardon [Username]` ingame.

You can also set up a whitelist, so only certain people can join. It's quite a powerful tool.
