### ISSUE TITLE
[BUG] HTTP request sent, awaiting response... 403 Forbidden

### ISSUE THREAD

**Issue by PBahner** [AlexProgrammerDE/balena-minecraft-server#71]
**Describe the bug**
After starting the pi the BalenaDashboard shows me following:
![image](https://user-images.githubusercontent.com/49592255/103348699-13f2d600-4a9b-11eb-80b1-991d7468842a.png)

**To Reproduce**
1. boot the pi with the balena-minecraft-server image
2. set "ENABLE_UPDATE" to "true"
3. check logs in the BalenaDashboard

**Expected behavior**
The minecraft service running without errors.

I rebootet the pi multiple times and I also set the "RAM" to "4G"

**Comment by AlexProgrammerDE** [comment]
I knew this was gonna happen. They removed the public access to the api and force us now to use their own api. I will be working on a fix soon.

**Comment by mjernejm** [comment]
Greetings,

can you please provide us with estimation for the issue to be resolved?
As it would be useful to know if we should find any other solution or just wait for the fix.

Thanks in advance,
Kind regards, Jernej

**Comment by AlexProgrammerDE** [comment]
@mjernejm i will probably work on it after New Year's Eve. Its some tricky getting of data in a row to get the actual download url. But i assume it won't be too hard.

**Comment by chronicblondiee** [comment]
I was able to work around this issue with by changing the wget for the server in \balena-minecraft-server\mc-server\start.sh
wget -O paper.jar -T 15 -c https://papermc.io/api/v2/projects/paper/versions/1.16.4/builds/354/downloads/paper-1.16.4-354.jar && break
it will break on new release but works as a manual work around for now tested it and it works pretty well

**Comment by AlexProgrammerDE** [comment]
@chronicblondiee yeah you are right. I will add this "fix" for now.

**Comment by AlexProgrammerDE** [comment]
For everyone intrested in what my plan for fixing this is:

They force us now to use their built in apii for downloading the file. My idea was using it to get the newest mc version, getting the latest build for it and downloading exactly that one file. They use json so i will have to parse the api data in the bash shell. I will probably store it in variables then.

**Comment by chrisys** [comment]
@AlexProgrammerDE I've got a script going that's working for this, will PR for your review

**Comment by johanjpk** [comment]
Sorry I'm not really used to the Balena part of this show. How to get this working on a running server?
