### ISSUE TITLE
Minecraft server on raspberry pi 4B 2GB version 

### ISSUE THREAD

**Issue by Macka323** [AlexProgrammerDE/balena-minecraft-server#74]
I tried to install Minecraft server but it didn't work on the raspberry pi 4B 2GB, is it supported or not, because it doesn't say anything on the GitHub page.

**Comment by AlexProgrammerDE** [comment]
> I tried to install Minecraft server but it didn't work on the raspberry pi 4B 2GB, is it supported or not, because it doesn't say anything on the GitHub page.

Did you get any error message or similar?

**Comment by Macka323** [comment]
It was a long time ago but I think it wouldn't install all of the necessary packages and the ram usage was 1.9/2 GB.

**Comment by AlexProgrammerDE** [comment]
> it wouldn't install all of the necessary packages and the ram usage was 1.9/2 GB.

hm that sounds weird. Linux normally doesn't take so much ram usage. Maybe its balena? I will check it myself later.

**Comment by hasan0610** [comment]
Oh my server is also using a lot of ram even with no users mine is using like 4gb with no one on it I need help tooo I have a small suspicion it has to do with the WiFi connect checking every 120 seconds
