### ISSUE TITLE
Server Customization Inquiry

### ISSUE THREAD

**Issue by c-condor** [AlexProgrammerDE/balena-minecraft-server#78]
You left links to various other Minecraft server flavors however am I correct in assuming those would not be compatible with this project? In addition while 1.16 is the current version; are there any ways to choose an older version to run such as 1.12 to use the RaspberryJuice Plugin for python interaction of the server using mcpi?

**Comment by AlexProgrammerDE** [comment]
> 
> 
> You left links to various other Minecraft server flavors however am I correct in assuming those would not be compatible with this project? In addition while 1.16 is the current version; are there any ways to choose an older version to run such as 1.12 to use the RaspberryJuice Plugin for python interaction of the server using mcpi?

I guess you could use each server software and also every version. The actual limit is your ram and the power of the cpu. Maybe try running a server on raspbian instead of balena if you need python and much stuff like that.
