### ISSUE TITLE
[FEATURE]how many people can connect?

### ISSUE THREAD

**Issue by gamerabbit16** [AlexProgrammerDE/balena-minecraft-server#79]
i want to connect with friends but we are 30 players

**Comment by AlexProgrammerDE** [comment]
@gamerabbit16 theoretically infinite. Make sure enough ram is allocated. You will probably face a hardware limit at 10 players, but i think 30 may be possible. https://tryitands.ee/

**Comment by gamerabbit16** [comment]
and 8 go ram
