### ISSUE TITLE
balena-rcon[BUG]

### ISSUE THREAD

**Issue by Crystalix2** [AlexProgrammerDE/balena-minecraft-server#84]
I can't seem to get any response to any commands other than /help

**To Reproduce**
1. Go to balena application summary 
2. Click on 'balena-rcon'
3. Type in command (e.g: /kill "playername")
4. "Unknown command. Type "/help" for help."

**Raspberry Pi:**
 - OS: [balenaOS 2.65.0+rev1]
 - Version [12.2.11]

**Minecraft (please complete the following information):**
 - Device: [Pc]
 - OS: [Windows10]
 - Minecraft Edition [Java Edition]
 - Minecraft Version [1.16.5]

**Comment by AlexProgrammerDE** [comment]
> Go to balena application summary

Have you tried just `kill playername`?
