### ISSUE TITLE
server overloaded?

### ISSUE THREAD

**Issue by InflictedRhyno** [AlexProgrammerDE/balena-minecraft-server#85]
i'm having dejavu's in my world
if i look things up ,nothing is in th red zone

I got a pi4 8GB , 
i gave MCserver 6GB
got 8GB Allocated in the launger.

i also see the following message

[date WARN]: Can't keep up! Is the server overloaded? running xxxxms or xxx ticks behind.

**Screenshots**
![image](https://user-images.githubusercontent.com/78094929/106058008-fa23cd80-60f0-11eb-85f3-babe186d8727.png)

**Raspberry Pi (please complete the following information):**
 - OS: [e.g. balenaOS 2.60.1+rev5]

**Minecraft (please complete the following information):**
 - Device: [DELL Precision3510]
 - OS: [window 10]
 - Minecraft Edition [e.g. Java Edition]
 - Minecraft Version [e.g. 1.16.5]

**Additional context**
What did i do wrong and if this can be fixed , any idea how?

**Comment by AlexProgrammerDE** [comment]
@InflictedRhyno yeah it seems like the Pi isn't the most fast pc on earth. You are moving fast, that means the Pi has to load a lot of data. The cpu isn't all that fast. What is the read and write speed of your micro sd card? May you try buying a faster one to see how it performs when data loads and writes faster?

**Comment by InflictedRhyno** [comment]
ah ha, all it says is Sandisk 16GB (i think its a 4) micro SDHC ,so i looked it up and it should be a 4 MB/s....and now i know why my friend ordered a class 10 card :p ... Thank you for all you've done over here .

**Comment by AlexProgrammerDE** [comment]
I will close this then
