### ISSUE TITLE
Server works on Mojang edition but not Windows 10 edition

### ISSUE THREAD

**Issue by Vanadium144** [AlexProgrammerDE/balena-minecraft-server#86]
**Describe the bug**
I have followed the complete guide on how to setup the server and get access to people outside of the LAN using port forwarding and NO-IP, however, only users within the Mojang version can connect, but anyone with the Windows 10 version cannot. Additionally, I can connect locally using the Mojang version but I cannot connect locally using the Windows 10 version despite using the same exact server information. One difference with the Windows 10 version that I noticed is that it forces you to include a port number where the mojang version does not

**Raspberry Pi (please complete the following information):**
 - OS: Balena OS
 - Version 2.65

**Minecraft (please complete the following information):**
 - Device: PC
 - OS: Windows 10
 - Minecraft Edition: Windows 10
 - Minecraft Version: 1.16

**Comment by AlexProgrammerDE** [comment]
@Vanadium144 the windows 10 edition and mojang version are two completely different things. Mojang edition is actually called `Java Edition`. Windows 10 is based on the `Bedrock edition`. What's the difference you may ask. Java edition is obviously written in java, but bedrock edition is written in C#. You may want to get a proxy such as GeyserMc to convert the bedrock edition packets (data minecraft servers exchange) to mojang edition packets.

**Comment by hasan0610** [comment]
U know if u want them both to work just install the plug-in geyser spigot it lets Java join bedrock and vice versa
