### ISSUE TITLE
Whitelist resets on launch

### ISSUE THREAD

**Issue by Pentagrade** [AlexProgrammerDE/balena-minecraft-server#9]
I've been encountering a problem where the `whitelist.json` file appears to be wiped on each full restart of the server. It's odd as things like the world and plugins folders don't appear to have the same problem.

Steps to reproduce:

- Install and start server following the instructions
- Whitelist a player
- Either restart the device remotely in balenaCloud or turn off the device physically and turn it back on
- Whitelist will be reset

**Comment by AlexProgrammerDE** [comment]
@Pentagrade can you check if the data is saved via SCP before rebooting? Maybe is the data only written to it if you stop it via RCON.

**Comment by Pentagrade** [comment]
That would make sense as it seems inconsistent.

**Comment by AlexProgrammerDE** [comment]
@Pentagrade i cant repoduce your issue. Did you set any variables like ENABLE_UPDATE?

**Comment by Pentagrade** [comment]
Yes it is enabled

**Comment by AlexProgrammerDE** [comment]
Thats the issue @Pentagrade it isn't only updating the server. It is also overwritting the config. Thats intended. It isn't deleting the whitelist.json. It is disabling it in the server.prperties file.

**Comment by Pentagrade** [comment]
Ahh that makes sense, I'll close this off then, thanks for looking into it
