### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by JacoVanR** [AlexProgrammerDE/balena-minecraft-server#93]
Hi i have my server set up and it great! no lags etc.
But i have a question can you use do multiple pi's?

**Comment by JacoVanR** [comment]
And if you can how do you do it?

**Comment by AlexProgrammerDE** [comment]
> can you use do multiple pi's?

You can. Just add more Pis into your balena fleet and the software should automatically deploy to those too.

**Comment by PeakMars** [comment]
Will the Pi's all run the one server? Or different servers?

**Comment by AlexProgrammerDE** [comment]
> 
> 
> Will the Pi's all run the one server? Or different servers?

One server per pi!

**Comment by PeakMars** [comment]
Ok, is there a way to make portals from one server to another (one Pi to another) so I can host certain worlds on one pi and the rest on the other? Also, I have alot of plugins on my server. Is there a downside to having may plugins?

**Comment by JacoVanR** [comment]
I want to like use multiple pi's to make one server.
Is that possible?

**Comment by AlexProgrammerDE** [comment]
> one server to another (one Pi to another) 
That requires a proxy such as bungeecord or waterfall. You connect to the proxy instead, and it will then connect to a server and send you there. If  trying to switch a server it fakes you connecting to the other server and moves your packets and data over.

**Comment by AlexProgrammerDE** [comment]
> I want to like use multiple pi's to make one server.
minecraft is firstly not multithreaded. That means it only uses one cpu core. It wouldn't work because you normally can't share a cpu core.

**Comment by AlexProgrammerDE** [comment]
> Is there a downside to having may plugins?

If those plugins are heavy or calculate a lot of stuff it may impact performance as I said above minecaft is single threaded, but if those plugins are properly written they could distribute the calculations over multiple cores and therefore have a less heavy impact on the server.
