### ISSUE TITLE
Wont allow me to connect using SCP[BUG]

### ISSUE THREAD

**Issue by Jonathanpou** [AlexProgrammerDE/balena-minecraft-server#96]
Im using FileZilla, when trying to connect to the serve it gives me an ssh_init error

<img width="888" alt="Skærmbillede 2021-02-11 kl  00 43 12" src="https://user-images.githubusercontent.com/34024791/107587471-20be2a00-6c02-11eb-9a01-214045b7308f.png">

My application in Balena cloud is called "minecraftServer" and even if i try using the host name "balenaminecraftserver" it still gives me the same error

**Raspberry Pi (please complete the following information):**
 - OS: [e.g. balenaOS 2.41.0+rev4]

**Minecraft (please complete the following information):**
 - Device: [Macbook pro mid 2014]
 - OS: [BIg Sur]
 - Minecraft Edition [e.g. Java Edition]
 - Minecraft Version [e.g. 1.16.1]

**Comment by AlexProgrammerDE** [comment]
![grafik](https://user-images.githubusercontent.com/40795980/107613911-93062d00-6c49-11eb-887e-51b1665bd69c.png)
@Jonathanpou sftp surely isn't scp. I would recommend using winscp instead if you are on Windows.

**Comment by AlexProgrammerDE** [comment]
Oh, I just checked it, and it actually seems like it is. Sorry. Try WinSCP tho

**Comment by Jonathanpou** [comment]
I will try WinSCP thx

**Comment by Jonathanpou** [comment]
FYI... Cyperduck(for mac) works if you use the ip address instead of application name
