### ISSUE TITLE
Forge 1.12.2 implementation

### ISSUE THREAD

**Issue by Devlah** [AlexProgrammerDE/balena-minecraft-server#97]
While Paper certainly is efficient, most popular modpacks still run on Forge 1.12.2
Having the option to install this variation would be greatly appreciated.

**Comment by Adriano72** [comment]
Yes, I'm trying to do that but no cue...

**Comment by hasan0610** [comment]
Ok easy
So basically download the forge.jar file 
Then open winscp login
Then in serverfiles look for paper.jar delete it
Then replace with forge.jar file then reboot server

**Comment by Domination987** [comment]
@hasan0610 
Okay so you replace the paper with forge, but how do you add a mod pack like ftb revelations or something like that?

**Comment by ARamlall** [comment]
If you get it to start properly with forge you should generate a mods and configs folder somewhere in there. I think you can pop the files into those folders from the ftb instances and restarting the server should generate the rest of the needed files. @Domination987 . My file kept getting replaced by paper so i just renamed the forge file as paper and got the file hash of that.
